import type { DesignPrompt, RawStudyTopic } from "./types";

export const foundationTopics: RawStudyTopic[] = [
  {
    id: "estimation",
    week: 1,
    day: 1,
    tier: 0,
    title: "Estimation & latency intuition",
    eyebrow: "Capacity before components",
    estimatedMinutes: 75,
    summary: "Turn product scale into QPS, bytes, bandwidth, concurrency, working-set size, and accelerator demand—then connect each number to a design decision.",
    whyItMatters: "A senior answer uses estimates to find the first bottleneck and remove impossible options. Arithmetic without an architectural consequence is theater.",
    objectives: ["Build dimensionally correct order-of-magnitude models", "Separate average load, peak load, skew, and failure headroom", "Translate capacity into partitions, replicas, cache, network, and compute"],
    concepts: ["Little’s Law", "Peak factor", "Working set", "Replication overhead", "Tail latency", "Usable throughput"],
    deepDive: [
      {
        title: "Model demand before fleet size",
        summary: "Start with units and a workload envelope, not server counts.",
        points: [
          "Average QPS = active users × operations per user per day ÷ 86,400. Model reads and writes separately because their storage and consistency paths differ.",
          "Peak is not a universal multiplier: consumer traffic follows time zones and events, batch traffic is scheduled, and reconnect storms correlate after failures. State the assumed peak and skew explicitly.",
          "For a stable system, Little’s Law gives average work inside a boundary: L = throughput × average total time in that boundary. Include queueing time when counting queued in-flight requests; use service time only for actively serviced work.",
        ],
      },
      {
        title: "Account for amplification",
        summary: "Logical traffic is rarely the physical work the system performs.",
        points: [
          "Physical storage includes replication, secondary indexes, metadata, compaction slack, erasure-coding overhead, and backups. Keep logical and physical numbers separate.",
          "A write may fan out to replicas, indexes, caches, event streams, and analytics. A feed write may additionally fan out to thousands of inboxes.",
          "Use p95 or p99 payload and sequence length for memory admission limits; the mean hides the requests most likely to exhaust a queue, heap, or KV cache.",
        ],
      },
      {
        title: "Turn estimates into thresholds",
        summary: "Every estimate should cause a decision or define a measurement to collect.",
        points: [
          "Compare the working set with effective cache capacity after replication and allocator overhead; this determines whether storage miss traffic is survivable.",
          "For accelerators, divide token demand by benchmarked throughput at the target latency and sequence mix—not peak FLOPS—and reserve headroom for failures and fragmentation.",
          "Name the sensitivity: if an unknown could change the architecture, bracket it and ask for a product measurement rather than inventing precision.",
        ],
      },
    ],
    tradeoffs: [
      { decision: "Precision vs speed", preferA: "Use one-significant-digit estimates when choosing architecture during an interview.", preferB: "Use a more detailed model for memory fit, cost commitments, or a hard SLO.", watch: "False precision can hide uncertainty in peak factor and skew." },
      { decision: "Headroom vs utilization", preferA: "Reserve capacity for correlated failures and fast traffic growth when availability matters.", preferB: "Run hotter when work is delay-tolerant and admission can shed load safely.", watch: "Average utilization says little about tail latency near saturation." },
      { decision: "Batching vs latency", preferA: "Batch offline or throughput-bound work to amortize fixed cost.", preferB: "Use bounded or continuous batching for interactive paths with tail-latency SLOs.", watch: "Unbounded queueing can erase the throughput gain." },
    ],
    failureModes: [
      { mode: "Capacity model uses only daily average", symptom: "Predictable peak-hour saturation and rising queue time", mitigation: "Model peak, skew, retry amplification, and one-failure-domain loss." },
      { mode: "Logical bytes are treated as physical bytes", symptom: "Unexpected disk, network, or backup cost", mitigation: "Add replication, indexes, compaction headroom, and retention copies explicitly." },
      { mode: "Benchmark throughput is used without the SLO workload", symptom: "Fleet meets tokens/s but misses p99 latency or OOMs on long inputs", mitigation: "Benchmark the actual request mix and enforce admission by memory-weighted work." },
    ],
    interviewQuestions: ["Which estimate can change the architecture?", "What happens to capacity during a zone failure?", "How does key or tenant skew alter the mean?", "Which assumption would you validate first in production?"],
    decisionChecklist: ["Write units on every intermediate value", "Separate average, peak, skew, and failure load", "Separate logical data from physical amplification", "State headroom and utilization target", "Name the architectural consequence"],
    exercise: "Estimate peak QPS, storage, cache working set, and regional failover load for a URL shortener serving 100 million redirects per day with a Zipf-like hot-link distribution.",
    prerequisites: ["Basic arithmetic", "Units and powers of ten"],
    relatedDesigns: ["URL shortener", "Chat", "Observability pipeline", "LLM inference service"],
    quiz: [
      { prompt: "At 20,000 requests/s and 80 ms average time inside the request-processing boundary, what is the average number of requests in that boundary?", options: ["250", "1,600", "20,080", "250,000"], answerIndex: 1, explanation: "Little’s Law: 20,000/s × 0.08 s = 1,600 requests on average inside the measured boundary." },
      { prompt: "Which number should drive cache sizing?", options: ["Total historical dataset", "Average object size only", "Hot working set during the design horizon plus overhead", "Daily write QPS"], answerIndex: 2, explanation: "A cache must hold enough of the active working set to achieve the assumed hit rate, including replication and allocator overhead." },
    ],
    recallCards: [
      { id: "est-littles-law", prompt: "State Little's Law, the condition it requires, and the mistake people make when applying it to a request path.", answer: "For a stable system, L = throughput x average time spent inside a stated boundary. It holds only in steady state and only for the boundary you actually measured. The common mistake is mixing boundaries: counting queued in-flight requests requires the total time including queueing, whereas service time alone gives only the actively-serviced concurrency. Naming the boundary before multiplying is what makes the number mean anything." },
      { id: "est-amplification", prompt: "Given a logical write volume, list the sources of physical amplification you must add before sizing storage.", answer: "Replication factor, secondary indexes, metadata, compaction slack and space amplification, erasure-coding overhead, and retained backup or snapshot copies. Separately, a single logical write may fan out to replicas, indexes, caches, event streams, and analytics, and a feed write may fan out to thousands of inboxes. Keep logical and physical numbers on separate lines so the amplification factor stays visible and arguable." },
    ],
  },
  {
    id: "consistency-idempotency",
    week: 1,
    day: 2,
    tier: 0,
    title: "Consistency, transactions & idempotency",
    eyebrow: "Guarantees by invariant",
    estimatedMinutes: 85,
    summary: "Choose guarantees per operation, define invariants at the source of truth, and make every externally retryable effect safe under ambiguity.",
    whyItMatters: "Network timeouts make outcomes uncertain. Senior designs distinguish delivery semantics from effect semantics and spend coordination only where a business invariant needs it.",
    objectives: ["Separate linearizability from serializability and isolation", "Apply CAP/PACELC to concrete operations", "Design idempotent writes across databases and queues"],
    concepts: ["Linearizability", "Serializability", "Snapshot isolation", "Causal consistency", "Idempotency key", "Fencing token", "Transactional outbox"],
    deepDive: [
      {
        title: "Name the guarantee precisely",
        summary: "Consistency has several independent dimensions.",
        points: [
          "Linearizability is real-time ordering of individual operations; serializability is equivalence to some serial transaction order. A database can offer serializable transactions without external real-time ordering.",
          "Snapshot isolation gives each transaction a consistent snapshot but can permit write skew unless the invariant is represented by a conflicting write or stronger isolation is used.",
          "CAP concerns behavior while a network partition exists; PACELC adds the normal-case latency-versus-consistency choice. Neither means a database is simply ‘CP’ for every operation.",
        ],
      },
      {
        title: "Make uncertain retries harmless",
        summary: "A timeout does not reveal whether the first attempt committed.",
        points: [
          "Bind an idempotency key to caller, operation, and normalized payload. Atomically store the key, payload hash, state, and eventual response with the business mutation.",
          "Concurrent duplicates must converge on the same result. Reject key reuse with a different payload; retain keys at least through the maximum retry and dispute window.",
          "Queues generally provide at-least-once delivery. Put deduplication or a unique business key at the effect boundary; exactly-once processing inside a broker does not make arbitrary external effects exactly once.",
        ],
      },
      {
        title: "Coordinate without stale owners",
        summary: "Locks need leases and fencing, not faith in process liveness.",
        points: [
          "Optimistic concurrency uses a version predicate in the write and retries a recomputation on conflict; it works well when contention is low and conflicts are safe to expose.",
          "A lease can expire while its holder is paused. A monotonically increasing fencing token lets the protected resource reject writes from an old holder.",
          "Use an outbox row committed with domain state, then relay it to the stream. Consumers remain idempotent because relay publication can repeat after a crash.",
        ],
      },
    ],
    tradeoffs: [
      { decision: "Strong vs eventual reads", preferA: "Use linearizable reads when a decision requires the latest committed state; enforce uniqueness, money, and inventory with conditional writes or serializable transactions.", preferB: "Use replicas or materialized views for feeds, presence, and analytics where staleness is bounded and visible.", watch: "Read strength alone does not make a read-then-write sequence atomic." },
      { decision: "Optimistic vs pessimistic concurrency", preferA: "Prefer version checks for low contention and short mutations.", preferB: "Prefer locks or serialized ownership for hot, correctness-critical resources.", watch: "Long transactions and lock convoys destroy latency." },
      { decision: "Synchronous side effect vs outbox", preferA: "Use a single transaction when the state and effect share one transactional resource.", preferB: "Use outbox plus idempotent consumer across storage or service boundaries.", watch: "Dual writes create missing or phantom events." },
    ],
    failureModes: [
      { mode: "Client times out after commit and retries", symptom: "Duplicate charge, order, or notification", mitigation: "Atomically persist an idempotency record and return its prior result." },
      { mode: "Snapshot-isolated transactions write skew", symptom: "Cross-row invariant violated despite no write-write conflict", mitigation: "Materialize the invariant into a conflicting row, lock the predicate, or use serializable isolation." },
      { mode: "Expired lock holder keeps writing", symptom: "New owner’s work is overwritten by a paused old process", mitigation: "Issue fencing tokens and reject stale epochs at the resource." },
    ],
    interviewQuestions: ["What exact invariant needs coordination?", "What does a caller do after an ambiguous timeout?", "Where is the idempotency record committed?", "Can a stale lease holder still mutate state?"],
    decisionChecklist: ["State invariants before consistency levels", "Classify each read/write path independently", "Specify retry identity and retention", "Put dedupe at the effect boundary", "Explain conflict and stale-owner handling"],
    exercise: "Specify guarantees and retry behavior for payment capture, inventory reservation, chat presence, profile updates, likes, and analytics ingestion.",
    prerequisites: ["Transactions", "Failure and timeout basics"],
    relatedDesigns: ["Payment ledger", "Notification system", "File synchronization", "Ad serving"],
    quiz: [
      { prompt: "A client times out after payment creation and retries with the same idempotency key but a different amount. What should the API do?", options: ["Create a second payment", "Overwrite the original request", "Reject the key reuse because the payload hash differs", "Wait for the key to expire"], answerIndex: 2, explanation: "The key identifies one logical operation. Reuse with different semantics must be rejected to prevent accidental aliasing." },
      { prompt: "Why is a lease alone insufficient for exclusive writes?", options: ["Leases cannot be replicated", "A paused holder may resume after expiry", "Clocks are always synchronized", "Leases require UDP"], answerIndex: 1, explanation: "A process can pause beyond its lease, then resume unaware that a new owner exists. The resource needs a fencing epoch." },
    ],
    recallCards: [
      { id: "con-lin-vs-ser", prompt: "Distinguish linearizability from serializability, and explain why a database can offer one without the other.", answer: "Linearizability is a real-time ordering guarantee on individual operations: once a write completes, every later read observes it. Serializability is an isolation guarantee that a set of transactions is equivalent to some serial order, with no requirement that the order match real time. A database can therefore provide serializable transactions while a read issued after a commit still misses it, because nothing ties the serial order to wall-clock ordering. Strict serializability is the combination of both." },
      { id: "con-idempotency-key", prompt: "Describe what an idempotency key must be bound to, what is stored with it, and how concurrent duplicates are handled.", answer: "Bind the key to caller, operation, and a hash of the normalized payload. Atomically persist the key, payload hash, state, and the eventual response in the same transaction as the business mutation, so the record cannot exist without the effect or vice versa. Concurrent duplicates must converge on one result, typically by having the loser wait on or read the winner's record. Reuse of the key with a different payload hash must be rejected rather than aliased, and keys are retained through the maximum retry and dispute window." },
    ],
    furtherReading: [{ label: "Herlihy & Wing — Linearizability", url: "https://cs.brown.edu/~mph/HerlihyW90/p463-herlihy.pdf" }],
  },
  {
    id: "replication-partitioning",
    week: 1,
    day: 3,
    tier: 0,
    title: "Replication, consensus & partitioning",
    eyebrow: "Scale data without losing ownership",
    estimatedMinutes: 90,
    summary: "Choose a replication protocol and partition key together, then describe leadership, quorum, rebalancing, hot-key isolation, and failover explicitly.",
    whyItMatters: "Most distributed storage failures are not solved by ‘add shards.’ The hard parts are ownership transitions, stale replicas, correlated load, and cross-partition invariants.",
    objectives: ["Distinguish consensus quorums from Dynamo-style quorums", "Select keys from access patterns and cardinality", "Narrate a safe reshard and regional failover"],
    concepts: ["Leader-follower", "Consensus log", "Term/epoch", "Leaderless quorum", "Consistent hashing", "Virtual node", "Hot partition", "Resharding"],
    deepDive: [
      { title: "Replication models", summary: "Replication semantics determine write ownership and conflict behavior.", points: ["In Raft, an entry from the leader’s current term becomes committed once replicated to a majority; quorum intersection plus the election log-freshness rule ensures later leaders contain committed entries.", "For fixed replica membership, R + W > N gives read/write quorum intersection, but not linearizability by itself; ordering versions and returning the latest completed write require an additional protocol. Sloppy quorums and asynchronous read repair weaken that guarantee.", "Multi-leader accepts writes in multiple sites and therefore needs deterministic conflict resolution, domain-specific merge, or user-visible conflicts. Last-write-wins can silently discard updates under clock skew.", "Paxos solves consensus on a single value through prepare/accept rounds with proposal numbers; Multi-Paxos amortizes the prepare phase across a stable leader, which is structurally what Raft prescribes with terms and an explicit log. Raft is not a different guarantee—it is the same safety made teachable by fixing leadership and log contiguity, which is why production systems built on either converge on a leader-based replicated log."] },
      { title: "Partition from access patterns", summary: "A high-cardinality key is necessary but not sufficient.", points: ["Hash partitioning spreads point traffic but loses range locality; range partitioning supports scans but concentrates sequential inserts and popular ranges.", "Co-locate data that must be transacted or read together, but avoid a tenant or celebrity key whose rate exceeds one partition’s capacity.", "Secondary indexes are local or global: local indexes scatter queries; global indexes add an asynchronously or transactionally maintained partitioned structure."] },
      { title: "Move ownership safely", summary: "Resharding is a protocol, not a metadata edit.", points: ["Introduce a new routing epoch, copy a consistent snapshot, stream the change log, validate lag/checksums, cut reads and writes, and retain rollback state.", "Clients and routers must tolerate stale maps via redirects or retries; fencing prevents an old owner from accepting writes after cutover.", "Throttle movement to protect foreground traffic. A failed node and its replicas must not all rebuild through the same constrained network link."] },
    ],
    tradeoffs: [
      { decision: "Hash vs range partitioning", preferA: "Hash for uniform point access and elastic distribution.", preferB: "Range for ordered scans and time/range locality.", watch: "Monotonic keys and hot tenants defeat naive range layouts." },
      { decision: "Leader vs leaderless writes", preferA: "Leader for ordered mutations, simpler transactions, and strong consistency.", preferB: "Leaderless for high write availability with resolvable conflicts.", watch: "Read repair does not prevent all stale reads or lost concurrent intent." },
      { decision: "Co-location vs distribution", preferA: "Co-locate transactional aggregates and common joins.", preferB: "Distribute extremely hot entities or independently scalable subresources.", watch: "Cross-shard coordination migrates complexity into transactions and operations." },
    ],
    failureModes: [
      { mode: "Hot key exceeds a partition", symptom: "One shard saturates while fleet utilization remains low", mitigation: "Cache, split by subkey/time, isolate the tenant, or aggregate through hierarchical ownership." },
      { mode: "Stale router writes to old owner", symptom: "Lost or divergent writes during resharding", mitigation: "Use routing epochs, redirects, and fencing at storage nodes." },
      { mode: "Replica rebuild saturates shared network", symptom: "Failover triggers wider latency and replication lag", mitigation: "Rate-limit repair, use diverse sources, and reserve recovery bandwidth." },
    ],
    interviewQuestions: ["What is the partition key for each dominant query?", "Who can accept a write during leadership change?", "How is a hot tenant split?", "How do stale routers learn a new map?"],
    decisionChecklist: ["Identify write owner and commit rule", "Map every query to a partition route", "Describe conflict/version semantics", "Plan snapshot plus change-log migration", "Test a hot key and one-zone loss"],
    exercise: "Design a key-value store’s replication and routing layers, including a live split of one hot partition without lost writes.",
    prerequisites: ["Consistency models", "Hashing"],
    relatedDesigns: ["Distributed cache", "Newsfeed", "Chat history", "Metrics platform"],
    quiz: [
      { prompt: "Why does a Raft entry committed in its leader’s current term survive leader change?", options: ["Every replica has every entry", "Majority intersection plus the election log-freshness rule", "The leader’s clock is authoritative", "Followers cannot fail"], answerIndex: 1, explanation: "The election quorum intersects the commit quorum, and Raft’s voting freshness rule prevents a candidate missing the committed log suffix from winning." },
      { prompt: "Which migration step closes the gap between a copied snapshot and current writes?", options: ["Longer cache TTL", "Change-log catch-up under an ownership epoch", "Random reads", "DNS failover"], answerIndex: 1, explanation: "A snapshot plus ordered change stream brings the destination current before fenced cutover." },
    ],
    recallCards: [
      { id: "rep-raft-commit", prompt: "State Raft's commit rule precisely and explain why the current-term qualifier matters.", answer: "An entry from the leader's current term is committed once it is replicated to a majority; entries from earlier terms are committed only indirectly, once an entry of the current term commits above them. The qualifier matters because a majority-replicated entry from a previous term can still be overwritten by a later leader, which is the figure-8 scenario Raft explicitly rules out. Safety comes from quorum intersection plus the election rule that a candidate missing committed entries cannot win." },
      { id: "rep-quorum-limit", prompt: "Explain what R + W > N does and does not guarantee.", answer: "With fixed replica membership it guarantees that read and write quorums intersect, so a read set contains at least one replica that saw the latest completed write. It does not by itself give linearizability: you additionally need version ordering and a rule for returning the latest completed write, and concurrent writes can still produce siblings. Sloppy quorums with hinted handoff and asynchronous read repair weaken the intersection property further, so the inequality alone is not a consistency guarantee." },
    ],
    furtherReading: [{ label: "Raft consensus paper", url: "https://raft.github.io/raft.pdf" }, { label: "Dynamo paper", url: "https://www.allthingsdistributed.com/files/amazon-dynamo-sosp2007.pdf" }],
  },
  {
    id: "networking",
    week: 1,
    day: 4,
    tier: 0,
    title: "Networking & service boundaries",
    eyebrow: "Trace every request hop",
    estimatedMinutes: 80,
    summary: "Explain the end-to-end request path and make protocols, load balancing, connection management, deadlines, retries, and backpressure part of the design.",
    whyItMatters: "A nominally healthy service can fail through connection pools, mismatched deadlines, retry amplification, or an overloaded dependency long before CPU reaches 100%. Open boxes matter.",
    objectives: ["Choose request, stream, and peer-to-peer protocols by semantics", "Budget deadlines and retries across hops", "Design connection and load-balancing behavior under failure"],
    concepts: ["TCP flow control", "HTTP/2 multiplexing", "gRPC deadline", "L4/L7 balancing", "Connection pool", "Retry budget", "Circuit breaker", "CDN"],
    deepDive: [
      { title: "Select transport from interaction shape", summary: "Protocol choice follows delivery, fan-out, browser, and latency needs.", points: ["HTTP request/response is operationally simple; gRPC adds typed contracts, streaming, and efficient binary framing for controlled clients; neither removes application-level compatibility.", "WebSockets provide a bidirectional, ordered message channel over a long-lived TCP connection and require gateway ownership plus reconnect/resume logic. WebRTC adds NAT traversal and media-oriented peer paths, usually with signaling and relay fallback.", "TCP guarantees ordered delivery, so one lost packet can delay later bytes on that connection. HTTP/2 multiplexes application streams but still shares the TCP loss domain."] },
      { title: "Propagate one end-to-end deadline", summary: "Independent per-hop timeouts create work after the caller has left.", points: ["The edge sets a deadline; each hop subtracts elapsed and reserve time. Downstream work should cancel when the deadline expires.", "Retry only transient, safe operations with exponential backoff, jitter, a maximum attempt count, and a fleet-wide retry budget. Hedging is reserved for idempotent tail-sensitive reads.", "Make overload explicit with bounded queues, concurrency limits, and retryable rejection. A circuit breaker cannot create capacity; it prevents repeated expensive failures."] },
      { title: "Operate connection-heavy systems", summary: "Connections are state and must be distributed deliberately.", points: ["Load balancing differs for short requests and long-lived sessions. Gateways register session ownership so a message router can find the connection without global broadcast.", "Pool limits protect dependencies but can become a hidden queue. Monitor wait time, active/idle counts, handshake rate, resets, and ephemeral-port pressure.", "Reconnects after a regional or network event must use server hints and randomized client backoff; otherwise recovery traffic can exceed steady-state traffic by orders of magnitude."] },
    ],
    tradeoffs: [
      { decision: "REST/JSON vs RPC/Protobuf", preferA: "REST/JSON for public, cacheable, human-debuggable interfaces.", preferB: "Typed RPC for high-volume internal contracts and streaming.", watch: "Schema evolution and deadline semantics matter more than encoding alone." },
      { decision: "L4 vs L7 load balancing", preferA: "L4 for low overhead and protocol transparency.", preferB: "L7 for request-aware routing, auth, retries, and observability.", watch: "L7 retries can multiply application retries." },
      { decision: "Persistent vs short connections", preferA: "Persistent for frequent interaction and server push.", preferB: "Short-lived stateless requests for simpler mobility and load balancing.", watch: "Idle memory, heartbeats, ownership, and reconnect storms." },
    ],
    failureModes: [
      { mode: "Nested retries amplify load", symptom: "Dependency slowdown causes traffic to multiply at every layer", mitigation: "Choose one retry owner, propagate deadlines, and enforce a retry budget." },
      { mode: "Pool exhaustion hides as service latency", symptom: "Requests wait before any network call while dependency CPU looks normal", mitigation: "Bound concurrency and instrument pool wait separately from wire latency." },
      { mode: "Reconnect storm after gateway loss", symptom: "Recovery repeatedly overloads authentication and session stores", mitigation: "Use jittered exponential reconnect, admission control, and session-resume tokens." },
    ],
    interviewQuestions: ["Where does the end-to-end deadline originate?", "Which layer owns retries?", "How does a router find a user’s live connection?", "What protects the service during reconnect?"],
    decisionChecklist: ["Draw DNS/TLS/edge/load-balancer hops", "Classify interaction as request, stream, or media", "Propagate deadlines and cancellation", "Bound pools, queues, and retries", "Describe reconnection and backpressure"],
    exercise: "Trace video playback, chat delivery, and an internal RPC from client to source of truth, including timeout and overload behavior at each hop.",
    prerequisites: ["TCP/IP basics", "Client-server model"],
    relatedDesigns: ["Chat", "Video streaming", "Notification system", "Inference gateway"],
    quiz: [
      { prompt: "A three-hop call stack allows three total attempts at every hop. Roughly how many leaf attempts can one request create?", options: ["3", "6", "9", "27"], answerIndex: 3, explanation: "Independent attempt budgets multiply: 3 × 3 × 3 = 27 leaf attempts. Centralize retry ownership and budget it." },
      { prompt: "What is the safest response to overload for nonessential work?", options: ["Add an unbounded queue", "Reject early with retry guidance and bounded admission", "Disable timeouts", "Retry immediately"], answerIndex: 1, explanation: "Bounded admission preserves useful work and prevents queueing collapse; clients should retry only with budget and jitter." },
    ],
    recallCards: [
      { id: "net-deadline", prompt: "Explain end-to-end deadline propagation and why independent per-hop timeouts are worse.", answer: "The edge sets one deadline for the whole request; each hop subtracts elapsed time plus a reserve before calling downstream, and cancels work when the deadline passes. Independent per-hop timeouts let a downstream hop keep working long after the caller has given up, burning capacity on results nobody will read, and they make the worst-case total the sum of every hop's timeout rather than a bounded budget." },
      { id: "net-retry-amplify", prompt: "Show how retries amplify across layers and state the mitigations.", answer: "Independent attempt budgets multiply: three hops each allowing three attempts yields up to 27 leaf attempts from one request, so a slow dependency sees load multiply exactly when it is least able to absorb it. Mitigate by choosing a single retry owner rather than retrying at every layer, enforcing a fleet-wide retry budget as a fraction of traffic, using exponential backoff with jitter, and propagating deadlines so a doomed request stops early." },
    ],
    furtherReading: [{ label: "HTTP/2 specification (RFC 9113)", url: "https://www.rfc-editor.org/rfc/rfc9113" }],
  },
  {
    id: "caching-queues",
    week: 2,
    day: 1,
    tier: 0,
    title: "Caching, logs & backpressure",
    eyebrow: "Control repeated and deferred work",
    estimatedMinutes: 90,
    summary: "Use caches to remove repeated work and queues or logs to decouple producers, while preserving freshness, ordering, retry safety, and bounded resource use.",
    whyItMatters: "Caches and queues improve the happy path but create new consistency states. Senior designs explain invalidation, lag, poison data, replay, and overload explicitly.",
    objectives: ["Choose a cache ownership and invalidation model", "Distinguish task queues from partitioned durable logs", "Design idempotent consumers and end-to-end backpressure"],
    concepts: ["Cache-aside", "Write-through", "Request coalescing", "Partitioned log", "Consumer group", "At-least-once", "Dead-letter", "Backpressure"],
    deepDive: [
      { title: "Treat cache entries as derived state", summary: "Freshness is a contract, not merely a TTL.", points: ["Cache-aside reads source on miss and populates; concurrent misses need request coalescing or probabilistic early refresh to avoid a stampede.", "Invalidation should carry a version when reordering is possible. A late invalidation or old fill must not overwrite a newer cached value.", "Negative caching protects repeated misses but needs shorter TTLs and invalidation on creation. Hot keys may require replication, local near-caches, or request collapsing."] },
      { title: "Choose queue or log by consumption semantics", summary: "Work distribution and event history are different abstractions.", points: ["A task queue transfers ownership of work and often deletes after acknowledgment (RabbitMQ, SQS). A durable partitioned log retains ordered records and lets independent consumer groups track offsets and replay (Kafka, Pulsar, Kinesis). Name the semantics you need before naming the product.", "Ordering is normally per partition, not global. The partition key must match the entity whose events need order; more partitions improve parallelism but weaken ordering scope.", "Acknowledgment after side effect avoids loss but permits duplicate delivery after a crash. The consumer must make the effect idempotent before advancing its durable position."] },
      { title: "Backpressure spans the entire path", summary: "A broker defers overload; it does not remove it.", points: ["Track lag in time, not only message count, because event value and processing cost vary. Define when work becomes too stale to execute.", "A retry topic delays a failed record and lets the main partition advance, but sacrifices strict per-key order unless later records are sequence-gated or the partition remains paused. Poison records still need owned quarantine and safe replay.", "Producers need admission, quotas, or degradation when consumers cannot catch up. Otherwise retained backlog eventually exhausts disk and recovery time." ] },
    ],
    tradeoffs: [
      { decision: "TTL vs event invalidation", preferA: "TTL for simple bounded staleness and resilience to missed events.", preferB: "Versioned invalidation for tighter freshness on mutable hot data.", watch: "Use both when invalidation delivery is not perfect." },
      { decision: "Queue vs durable log", preferA: "Queue for competing workers and one logical processing path.", preferB: "Log for replay, audit, ordered state propagation, and multiple consumers.", watch: "Retention and per-key ordering requirements drive the choice." },
      { decision: "Strict ordering vs throughput", preferA: "One partition per ordered entity when transitions depend on sequence.", preferB: "Spread independent work across partitions for scale.", watch: "A global partition becomes a throughput and availability bottleneck." },
    ],
    failureModes: [
      { mode: "Cache stampede on expiry", symptom: "Source traffic spikes exactly at TTL boundaries", mitigation: "Use jittered expiry, request coalescing, soft TTL, and stale-if-error." },
      { mode: "Poison event blocks ordered partition", symptom: "Lag grows behind one repeatedly failing record", mitigation: "Bound attempts, quarantine with metadata, and preserve a controlled replay path." },
      { mode: "Duplicate delivery repeats side effect", symptom: "Double charge or duplicate notification after consumer crash", mitigation: "Use an idempotency/business key atomically at the effect boundary." },
    ],
    interviewQuestions: ["What is authoritative when cache and source disagree?", "Which key requires ordering?", "When is stale work discarded?", "How is a quarantined event repaired and replayed?"],
    decisionChecklist: ["Define source of truth and freshness bound", "Choose fill, invalidation, and stampede policy", "State delivery and ordering scope", "Make effects idempotent", "Bound lag, retries, and queue size"],
    exercise: "Design the event and cache paths for a payment status page where updates may be duplicated, delayed, or delivered out of order.",
    prerequisites: ["Idempotency", "Partitioning"],
    relatedDesigns: ["Notification system", "Payment ledger", "Newsfeed", "Metrics pipeline"],
    quiz: [
      { prompt: "A consumer writes to a database and crashes before acknowledging. What must the design expect?", options: ["The event is lost", "The event may be delivered again", "The broker rolls back the database", "Global order is restored"], answerIndex: 1, explanation: "Acknowledgment did not persist, so an at-least-once broker redelivers. The database effect must be idempotent." },
      { prompt: "What should determine a stream partition key?", options: ["Alphabetical order", "The entity boundary that needs ordered processing", "The largest payload", "The current consumer count"], answerIndex: 1, explanation: "Events for the same stateful entity belong to the same ordered partition; independent entities can be parallelized." },
    ],
    recallCards: [
      { id: "cache-stampede", prompt: "Describe what happens when a hot key expires under load and the mitigations.", answer: "Every concurrent request misses simultaneously and stampedes the origin, which can be far more load than steady state and can cascade into a full outage. Mitigate with request coalescing so one filler populates the entry while others wait, probabilistic or jittered early expiry so keys do not expire in lockstep, serving stale while revalidating in the background, and admission limits on origin fills. The cache must also be sized against the hot working set, not the whole dataset." },
      { id: "cache-queue-vs-log", prompt: "Contrast a task queue with a durable partitioned log by consumption semantics.", answer: "A task queue transfers ownership of a unit of work and typically deletes it after acknowledgment, so there is one logical consumer and no history. A durable partitioned log retains an ordered sequence and lets independent consumer groups track their own offsets and replay from any point, which is what enables adding a new consumer or reprocessing after a bug. Ordering in a log is per partition, not global, so the partition key must match the entity whose events require order." },
    ],
  },
  {
    id: "storage-indexing",
    week: 2,
    day: 2,
    tier: 0,
    title: "Storage engines & indexing",
    eyebrow: "Access patterns choose the database",
    estimatedMinutes: 95,
    summary: "Derive the data model, primary key, indexes, partitioning, retention, and engine shape from access patterns and correctness—not a product name.",
    whyItMatters: "The wrong key or index can dominate a design at scale. Senior candidates explain physical read/write paths, amplification, compaction, and analytical separation.",
    objectives: ["Map workload shape to relational, KV, wide-column, object, search, vector, or analytical storage", "Compare B-tree and LSM write/read paths", "Budget secondary indexes, retention, and compaction"],
    concepts: ["Primary key", "Covering index", "B+ tree", "Write-ahead log", "Memtable", "SSTable", "Compaction", "Bloom filter", "Columnar storage"],
    deepDive: [
      { title: "Select from query and mutation shape", summary: "Begin with authoritative entities and dominant access paths.", points: ["Relational storage fits transactional invariants and indexed joins; key-value or wide-column storage fits predictable partition-key access at large scale; object storage fits immutable large blobs.", "Search indexes and vector indexes are derived serving structures, not usually the system of record. Rebuild them from versioned source data and an ordered change stream.", "Columnar analytical stores minimize scans through projection and compression; mixing long scans with latency-sensitive transactions causes resource interference."] },
      { title: "Understand the physical write path", summary: "B-trees and LSM trees move cost to different phases.", points: ["A conventional WAL-based B+ tree updates sorted pages in place, serving point/range reads predictably but causing random I/O and page splits under writes; copy-on-write variants move the durability cost differently.", "An LSM tree appends to a log and memtable, flushes immutable sorted runs, then compacts them. It trades high write throughput for read and space amplification plus background I/O.", "Bloom filters rule out absent keys probabilistically and reduce run reads; they never prove presence and false-positive rate costs memory."] },
      { title: "Treat indexes as derived views", summary: "Each index improves one query by taxing writes, storage, and consistency.", points: ["A composite index follows its leading columns; order fields by equality/range and sort requirements, not by schema aesthetics.", "A global secondary index must be partitioned and maintained. If asynchronous, queries need defined lag and repair; if transactional, writes pay coordination.", "Retention and deletion interact with compaction, snapshots, backups, search copies, and embeddings. A tombstone is not immediate physical erasure.", "A regulatory erasure request (GDPR right to erasure, CCPA deletion) must reach every derived copy: caches, search indexes, analytical warehouses, embeddings, backups, and logs. Track a deletion through a durable request record with per-sink completion, and prefer crypto-shredding a per-subject key where a backup cannot be rewritten." ] },
    ],
    tradeoffs: [
      { decision: "Relational vs non-relational", preferA: "Choose relational when the workload needs multi-row transactions, evolving ad-hoc queries, joins, and declarative constraints enforced by the engine.", preferB: "Choose a non-relational engine when one dominant access pattern, horizontal write scale, or a flexible/sparse shape outweighs those guarantees.", watch: "“SQL vs NoSQL” is not a decision—name the access pattern, the invariant, and the scale that force the choice, since managed relational engines now shard and non-relational engines now offer transactions." },
      { decision: "B-tree vs LSM", preferA: "B-tree for predictable point/range reads and moderate writes.", preferB: "LSM for sustained write throughput and sequential I/O.", watch: "Compaction can produce latency cliffs and temporary space amplification." },
      { decision: "Normalized vs denormalized", preferA: "Normalize authoritative transactional data and evolving relations.", preferB: "Denormalize stable serving views for bounded read latency.", watch: "Every copy needs freshness, repair, and deletion semantics." },
      { decision: "Synchronous vs asynchronous secondary index", preferA: "Synchronous when a query participates in a correctness invariant.", preferB: "Asynchronous for scalable discovery/search with explicit lag.", watch: "Do not read an async index to enforce uniqueness." },
    ],
    failureModes: [
      { mode: "Unbounded secondary-index fan-out", symptom: "Write latency and storage rise faster than source records", mitigation: "Keep only query-justified indexes and move exploratory queries to analytical/search views." },
      { mode: "Compaction competes with foreground I/O", symptom: "Periodic p99 spikes and growing space amplification", mitigation: "Throttle and schedule compaction, isolate resources, and alert on debt." },
      { mode: "Derived index accepted as source of truth", symptom: "Missing or stale documents cause irreversible decisions", mitigation: "Retain an authoritative store and reconcile versioned derived indexes." },
    ],
    interviewQuestions: ["List the exact read and write queries.", "Which field is the partition key and why?", "How stale may each index be?", "What happens to latency during compaction or backfill?"],
    decisionChecklist: ["Declare authoritative and derived stores", "Write key and index shapes for each query", "Estimate index and replication amplification", "Explain engine read/write paths", "Define retention, backfill, and repair"],
    exercise: "Choose and justify storage, keys, and indexes for a ledger, chat history, file blobs, high-cardinality metrics, embeddings, and a document search corpus.",
    prerequisites: ["Replication and partitioning", "Access-pattern analysis"],
    relatedDesigns: ["Payment ledger", "Chat", "File sync", "Search", "RAG"],
    quiz: [
      { prompt: "What does an LSM Bloom filter tell the reader?", options: ["The key is definitely present", "The key is definitely absent when the filter says absent", "The newest value", "Which replica is leader"], answerIndex: 1, explanation: "Bloom filters have false positives but no false negatives under correct construction; ‘absent’ avoids checking that run." },
      { prompt: "Why should an async search index not enforce username uniqueness?", options: ["Search cannot store strings", "Index lag allows concurrent duplicates", "Search indexes are always in memory", "Uniqueness needs compression"], answerIndex: 1, explanation: "An eventually updated index can miss a just-created value. Enforce the invariant transactionally at the source of truth." },
    ],
    recallCards: [
      { id: "store-btree-lsm", prompt: "Compare B-tree and LSM read/write paths and their characteristic operational risk.", answer: "A B-tree updates pages in place, giving predictable point and range reads and bounded read amplification, but random write I/O and page-level write amplification. An LSM buffers writes in memory and flushes sorted runs, giving high sequential write throughput at the cost of read amplification across levels, mitigated by bloom filters. The LSM's characteristic risk is compaction: it competes with foreground I/O and produces periodic latency cliffs and temporary space amplification." },
      { id: "store-erasure", prompt: "Explain why a tombstone is not erasure and what a regulatory deletion request must reach.", answer: "A tombstone marks a row logically deleted so reads skip it, but the bytes persist until compaction rewrites the affected files, and they may still exist in snapshots and backups. A regulatory erasure request must therefore reach every derived copy: caches, search indexes, analytical warehouses, embeddings, backups, and logs. Track it as a durable request record with per-sink completion, and where a backup cannot be rewritten, crypto-shred by destroying a per-subject key." },
    ],
    furtherReading: [{ label: "The Log-Structured Merge-Tree paper", url: "https://www.cs.umb.edu/~poneil/lsmtree.pdf" }, { label: "Bigtable paper", url: "https://static.googleusercontent.com/media/research.google.com/en//archive/bigtable-osdi06.pdf" }],
  },
  {
    id: "timed-designs",
    week: 2,
    day: 4,
    tier: 0,
    title: "Timed design execution",
    eyebrow: "Turn knowledge into a 45-minute argument",
    estimatedMinutes: 100,
    summary: "Drive a consistent interview structure, make assumptions visible, choose one valuable deep dive, and close with failure behavior and evolution.",
    whyItMatters: "Senior performance is evaluated as much by prioritization and communication as component recall. A coherent, testable argument beats an encyclopedic diagram.",
    objectives: ["Reach an end-to-end architecture by minute 20", "Select a deep dive from the hardest requirement", "Narrate trade-offs, degradation, and 10× evolution"],
    concepts: ["Requirements envelope", "Critical path", "Source of truth", "Invariant", "Deep dive", "Failure injection", "Two-minute close"],
    deepDive: [
      { title: "Control the first fifteen minutes", summary: "Align scope before drawing a fleet.", points: ["Clarify users, core operations, nonfunctional SLOs, data guarantees, security, and exclusions. Repeat the chosen scope to the interviewer.", "Estimate only architecture-changing dimensions, then define contracts and the authoritative data model.", "Draw the critical request path first. Add asynchronous and analytical paths only after the source-of-truth flow is coherent."] },
      { title: "Earn the deep dive", summary: "Choose depth from the design’s dominant risk.", points: ["For payments, choose idempotency and ledger invariants; for feeds, fan-out and hot users; for ML, labels and serving; for LLMs, memory and scheduling.", "State two options, the requirement that differentiates them, and the cost of the choice. Avoid presenting a tool as the rationale.", "Inject a failure while explaining: timeout after commit, duplicate event, hot key, slow replica, zone loss, or overloaded GPU queue."] },
      { title: "Close like an owner", summary: "Summarize guarantees and the next bottleneck.", points: ["Restate the main flow, source of truth, and one deliberate trade-off. Name what is strongly consistent and what is derived.", "Give concrete SLIs, an overload mode, and recovery or rollback behavior.", "At 10×, identify the first constrained resource and the measurement that would trigger the next architecture change." ] },
    ],
    tradeoffs: [
      { decision: "Breadth vs depth", preferA: "Cover the end-to-end path and all correctness boundaries first.", preferB: "Spend remaining time on the requirement with the highest technical risk.", watch: "Premature depth can leave the system incomplete." },
      { decision: "Assumption vs clarification", preferA: "Assume a reversible detail after stating it.", preferB: "Clarify scale, invariants, and SLOs that change architecture.", watch: "Do not burn time asking low-impact product questions." },
      { decision: "Current design vs future scale", preferA: "Build the simplest design meeting the stated envelope.", preferB: "Describe an evolution trigger for plausible 10× growth.", watch: "Prebuilding hypothetical scale obscures the core design." },
    ],
    failureModes: [
      { mode: "Component list without data flow", symptom: "Diagram sounds plausible but writes, reads, and ownership are ambiguous", mitigation: "Walk one request and one state transition end to end." },
      { mode: "No explicit invariant or SLO", symptom: "Trade-offs cannot be evaluated", mitigation: "Write the correctness and user-visible targets before selecting mechanisms." },
      { mode: "No reliability close", symptom: "Happy path consumes the full interview", mitigation: "Reserve five minutes and use a standard failure/observability/evolution checklist." },
    ],
    interviewQuestions: ["What is the single hardest requirement?", "Which component owns authoritative state?", "What breaks first at 10×?", "What would the user observe during regional failure?"],
    decisionChecklist: ["Timebox six interview phases", "State scope and assumptions", "Walk the critical path", "Deep-dive one differentiating mechanism", "Close with SLOs, failure, cost, and evolution"],
    exercise: "Complete the URL shortener and distributed rate limiter in 40–45 minutes each, recording only the three mistakes that would most improve the next attempt.",
    prerequisites: ["Week 1 topics 1–6"],
    relatedDesigns: ["URL shortener", "Distributed rate limiter"],
    quiz: [
      { prompt: "By roughly what point should a 45-minute answer have an end-to-end architecture?", options: ["Minute 5", "Minute 20", "Minute 40", "Only after every estimate is exact"], answerIndex: 1, explanation: "Reaching a coherent high-level flow near minute 20 preserves time for a meaningful deep dive and reliability." },
      { prompt: "What makes a trade-off explanation senior-level?", options: ["Naming the newest product", "Listing both options only", "Connecting a requirement to a choice and its cost", "Avoiding a decision"], answerIndex: 2, explanation: "A trade-off is useful when the interviewer can see which requirement drove the choice and what the system gives up." },
    ],
    recallCards: [
      { id: "timed-clock", prompt: "Give the phase budget for a 45-minute design and the checkpoint that tells you that you are behind.", answer: "Roughly: clarify 3-5 minutes, estimate 3-5, APIs and data model 3-5, end-to-end architecture 5-7, deep dive 15-20, and reliability close about 5. The checkpoint is having a coherent end-to-end flow by roughly minute 20; if the high-level architecture is not standing by then, the deep dive and the reliability close will both be sacrificed, which are exactly the parts that produce senior signal." },
      { id: "timed-tradeoff", prompt: "State what makes a trade-off answer read as senior rather than encyclopedic.", answer: "Name two viable options, identify the specific requirement that discriminates between them, commit to a choice, and state what the choice costs and under what measurement you would revisit it. Listing both options without deciding reads as indecision; naming a product as the rationale reads as pattern matching. The interviewer is looking for the causal link from a stated requirement to a decision and its consequence." },
    ],
  },
  {
    id: "auth-identity-access",
    week: 2,
    day: 3,
    tier: 0,
    title: "Identity, sessions & access control",
    eyebrow: "Prove who, then decide what",
    estimatedMinutes: 80,
    summary: "Separate authentication from authorization, choose between stateful sessions and self-contained tokens, and design revocation, delegation, and service-to-service identity deliberately.",
    whyItMatters: "Almost every design interview reaches “how do you authenticate this?” A weak answer names JWT and stops. A senior answer explains where trust originates, how it is scoped, and how it is revoked before its natural expiry.",
    objectives: ["Distinguish authentication, authorization, and delegation", "Choose session or token architecture from revocation and scale requirements", "Model permissions for multi-tenant and hierarchical resources", "Design service-to-service identity without shared long-lived secrets"],
    concepts: ["OAuth 2.0", "OpenID Connect", "JWT", "opaque session", "refresh token", "RBAC", "ReBAC", "mTLS", "token revocation"],
    deepDive: [
      {
        title: "Authentication, authorization, and delegation are different problems",
        summary: "Conflating them produces designs that cannot answer who granted what to whom.",
        points: [
          "Authentication establishes an identity; authorization decides whether that identity may perform an action on a resource. OAuth 2.0 is a delegation framework, not an authentication protocol—OpenID Connect is the identity layer built on top of it.",
          "An access token says what the bearer may do; an ID token says who signed in. Using an access token as proof of identity, or accepting a token whose audience names a different service, is a routine and serious mistake.",
          "Validate issuer, audience, expiry, signature, and algorithm against an allowlist. Never trust the token's own `alg` header to select verification, and fetch signing keys from a cached, rotated JWKS endpoint.",
        ],
      },
      {
        title: "Stateful sessions versus self-contained tokens",
        summary: "The choice is fundamentally about revocation latency versus lookup cost.",
        points: [
          "An opaque session ID carries no claims; every request resolves it against a session store. Revocation is immediate because the record is deleted, at the cost of a lookup on the hot path.",
          "A signed JWT is verifiable without I/O, so it scales horizontally—but it stays valid until it expires. You cannot un-issue it. Short access-token lifetimes plus a longer refresh token bound to a revocable server-side record recover most of the control.",
          "If you add a denylist check to make JWTs revocable, you have reintroduced the lookup and kept the complexity. Choose deliberately, and state the maximum window during which a compromised credential remains usable.",
        ],
      },
      {
        title: "Model permissions and machine identity",
        summary: "Authorization data has its own consistency and latency requirements.",
        points: [
          "RBAC assigns permissions through roles and is simple to reason about; relationship-based models answer questions like “can this user view this document because they belong to a folder's group,” which flat roles cannot express without combinatorial explosion.",
          "Centralized policy evaluation gives one auditable decision point but adds a hot dependency; distributed evaluation with replicated policy is fast but makes revocation eventually consistent. Name the staleness window—a removed employee should not keep read access for minutes.",
          "For service-to-service calls, prefer short-lived workload credentials (mTLS certificates or federated tokens) over shared static API keys. Propagate the end-user identity separately from the calling service identity so authorization can consider both.",
        ],
      },
    ],
    tradeoffs: [
      { decision: "Opaque session vs self-contained token", preferA: "Use server-side sessions when instant revocation and fine-grained control matter.", preferB: "Use signed tokens for stateless horizontal scale and cross-service verification.", watch: "A revocation denylist on a JWT recreates the session lookup you tried to avoid." },
      { decision: "Centralized vs distributed authorization", preferA: "Centralize for auditability and consistent policy.", preferB: "Distribute replicated policy for latency and blast-radius isolation.", watch: "Replicated policy makes permission removal eventually consistent." },
      { decision: "Long vs short token lifetime", preferA: "Short access tokens bound the damage of a leaked credential.", preferB: "Longer lifetimes reduce refresh traffic and identity-provider load.", watch: "Refresh storms after a mass expiry can overload the auth service." },
    ],
    failureModes: [
      { mode: "Token accepted without audience validation", symptom: "A token minted for one service is replayed against another", mitigation: "Validate issuer and audience per service and reject unexpected values." },
      { mode: "Revoked user retains access until expiry", symptom: "Offboarded account still reads data for the token lifetime", mitigation: "Shorten access-token life, bind sessions to a revocable record, and propagate revocation events." },
      { mode: "Permission check runs after data is fetched", symptom: "Authorization filters results the caller already loaded, leaking through timing or error differences", mitigation: "Push the authorization predicate into the query and fail closed on policy-store errors." },
    ],
    interviewQuestions: ["Where does trust originate for this request?", "How long can a compromised credential remain usable?", "Who may act on behalf of whom, and how is that recorded?", "What happens if the policy store is unavailable?"],
    decisionChecklist: ["Separate authentication from authorization explicitly", "State the revocation window", "Validate issuer, audience, expiry, and algorithm", "Choose a permission model that fits resource shape", "Give services their own short-lived identity"],
    exercise: "Design authentication and authorization for a multi-tenant document product where users share folders across organizations, and state exactly how access is removed within one minute of offboarding.",
    prerequisites: ["Networking & service boundaries", "Caching fundamentals"],
    relatedDesigns: ["File storage and synchronization", "Enterprise RAG assistant", "Payment ledger"],
    quiz: [
      { prompt: "Why is OAuth 2.0 alone insufficient to authenticate a user?", options: ["It is deprecated", "It is a delegation framework; OpenID Connect adds the identity layer", "It only works for mobile clients", "It cannot issue tokens"], answerIndex: 1, explanation: "OAuth 2.0 authorizes access to resources. OIDC layers on an ID token with verified identity claims, which is what authentication requires." },
      { prompt: "What is the main operational cost of self-contained JWTs?", options: ["They cannot be signed", "They require a database read per request", "They stay valid until expiry and cannot be un-issued", "They only work over HTTP/1.1"], answerIndex: 2, explanation: "Stateless verification is the benefit and the cost: without a lookup there is nothing to delete, so revocation is bounded by token lifetime." },
    ],
    recallCards: [
      { id: "auth-revocation", prompt: "Explain the revocation trade-off between opaque sessions and JWTs, and how short access tokens plus refresh tokens resolve it.", answer: "An opaque session resolves against a store on every request, so deleting the record revokes access immediately at the cost of a hot-path lookup. A signed JWT verifies with no I/O and scales horizontally, but nothing can un-issue it before expiry. Issuing short-lived access tokens against a longer refresh token bound to a revocable server-side record keeps stateless verification on the hot path while bounding compromise to the access-token lifetime." },
      { id: "auth-validation", prompt: "List what must be validated on an incoming JWT, and name the validation mistake that enables cross-service replay.", answer: "Validate issuer, audience, expiry/not-before, signature, and the algorithm against a server-side allowlist, using keys from a cached rotating JWKS. Never let the token's own alg header choose the verification method. Skipping audience validation is what enables replay: a token legitimately minted for service A is presented to service B, which accepts it because it only checked the signature." },
    ],
    furtherReading: [
      { label: "RFC 6749 — OAuth 2.0", url: "https://www.rfc-editor.org/rfc/rfc6749" },
      { label: "RFC 9068 — JWT access tokens", url: "https://www.rfc-editor.org/rfc/rfc9068" },
    ],
  },
];

export const foundationPrompts: DesignPrompt[] = [
  {
    id: "url-shortener",
    title: "URL shortener",
    category: "classic",
    difficulty: "medium",
    durationMinutes: 40,
    prompt: "Design a globally available service that creates short URLs and redirects readers with very low latency. Support expiration, abuse controls, editable destinations, and asynchronous analytics.",
    requirementsToExplore: ["Custom aliases and ownership", "Redirect latency and availability", "Read-after-create behavior", "Expiration and deletion", "Analytics freshness", "Malware and abuse response"],
    expectedTopics: ["Code generation and collision policy", "Authoritative mapping schema", "Cache coherence", "Hot-link isolation", "Multi-region routing", "Asynchronous click events"],
    commonFailureModes: ["Sequential codes expose volume or become predictable", "Negative caching hides newly created aliases", "Editable links remain stale in edge caches", "A celebrity link overloads one shard", "Analytics blocks the redirect path"],
    followUpQuestions: ["How do you migrate to a longer code space?", "How do you bound read-after-write inconsistency across regions?", "What happens when abuse policy disables a heavily cached link?", "How would one customer bring a custom domain?"],
    reference: {
      diagram: {
        caption: "Redirect reads are served from edge cache with the partitioned link store as source of truth; click analytics and cache invalidation both ride asynchronous streams so neither can slow a redirect.",
        nodes: [
          { id: "client", label: "Client", kind: "client", col: 0, row: 1 },
          { id: "api", label: "Create & manage API", kind: "service", col: 1, row: 0 },
          { id: "redirect", label: "Edge redirect service", kind: "edge", col: 1, row: 2 },
          { id: "store", label: "Link store (hash-partitioned)", kind: "store", col: 2, row: 0 },
          { id: "cache", label: "Regional read cache", kind: "cache", col: 2, row: 2 },
          { id: "clicks", label: "Click event stream", kind: "stream", col: 1, row: 3 },
          { id: "log", label: "Change log (CDC)", kind: "stream", col: 3, row: 0 },
          { id: "analytics", label: "Analytics & abuse views", kind: "store", col: 3, row: 3 },
        ],
        edges: [
          { from: "client", to: "api", label: "POST /links" },
          { from: "client", to: "redirect", label: "GET /{code}" },
          { from: "api", to: "store", label: "cond. write" },
          { from: "redirect", to: "cache", label: "lookup" },
          { from: "cache", to: "store", label: "miss" },
          { from: "redirect", to: "clicks", label: "click", async: true },
          { from: "clicks", to: "analytics", label: "aggregate", async: true },
          { from: "store", to: "log", label: "CDC", async: true },
          { from: "log", to: "cache", label: "invalidate", async: true },
        ],
      },
      scope: ["Separate create/update management availability from redirect availability", "Define whether aliases are case-sensitive and reusable after deletion", "Keep click analytics off the redirect critical path"],
      apis: ["POST /links with destination, optional alias, expiry, idempotency key", "GET /{code} returns 301/302/307 according to editability and caching policy", "PATCH /links/{code} uses owner auth and expected version", "DELETE /links/{code}; analytics query reads a derived store"],
      dataModel: ["Link(code PK, destination, owner_id, created_at, expires_at, status, version)", "Unique(owner_domain, normalized_code) enforces aliases at the source", "ClickEvent(code, event_id, time_bucket, coarse_geo, referrer_class) with privacy retention", "AbuseState(code, verdict, policy_version) distributed through versioned invalidation"],
      architecture: ["Create service validates and reserves a code in the authoritative partitioned store", "Change log invalidates regional caches and updates abuse/search views", "Edge redirect service reads local cache, falls back to a regional replica/source, then emits a best-effort event", "Stream processors aggregate clicks into time-bucketed analytical storage", "Control plane manages domains, policy, and deletion independently of redirect serving"],
      invariants: ["A normalized alias maps to at most one live link", "An idempotent create returns the same code for the same request", "An older cache fill cannot overwrite a newer mapping version", "Analytics loss or slowness never blocks redirect correctness"],
      deepDives: [
        { title: "Code space", summary: "Use random or allocated numeric identifiers encoded compactly.", points: ["Seven base-62 characters provide about 3.5 trillion values; choose length from expected population and acceptable collision probability.", "Random codes need conditional insert and retry; allocated 64-bit IDs need range leasing or a Snowflake-like generator and may require obfuscation."] },
        { title: "Freshness", summary: "Mutable destinations change HTTP and cache semantics.", points: ["Immutable links can use long TTL and permanent redirects; editable links need bounded TTL, mapping versions, and versioned invalidations.", "For read-after-create, route the creator to the write region, return a consistency token, or synchronously place the mapping in the local serving cache."] },
        { title: "Hot and harmful links", summary: "The most popular key and fastest takedown drive the edge design.", points: ["Replicate hot cache entries across edge workers and coalesce misses; never let one cache key serialize all traffic.", "Abuse verdicts need a high-priority invalidation path and a short-lived deny cache; define fail-open versus fail-closed by threat level."] },
      ],
      scaling: ["Partition mappings by a hash of normalized code", "Replicate read-serving data regionally and cache at edge", "Precompute or lease ID ranges to avoid a central generator bottleneck", "Rate-limit creates and isolate tenants", "Move analytics through a partitioned stream with bounded retention"],
      observability: ["Redirect p50/p99 and success by region", "Cache hit ratio, miss coalescing, and stale-version rejection", "Create collision/conditional-write rate", "Hot-key traffic distribution", "Replication and invalidation lag", "Event drop rate and abuse-takedown propagation time"],
    },
  },
  {
    id: "distributed-rate-limiter",
    title: "Distributed rate limiter",
    category: "classic",
    difficulty: "medium",
    durationMinutes: 40,
    prompt: "Design a low-latency rate limiter for public APIs with per-user, per-tenant, and endpoint policies. Support bursts, regional deployment, live policy changes, and explicit dependency-failure behavior.",
    requirementsToExplore: ["Key and enforcement scope", "Sustained rate and burst allowance", "Accuracy and overshoot budget", "Added latency", "Policy propagation", "Fail-open/closed by endpoint"],
    expectedTopics: ["Token bucket", "Sliding-window approximation", "Atomic state transition", "Local token leasing", "Clock semantics", "Hot-tenant isolation", "Degraded mode"],
    commonFailureModes: ["One remote counter is on every critical path", "Fixed windows allow a boundary burst", "Clock rollback refills tokens", "Policy cache remains stale", "Limiter outage either drops everything or admits everything"],
    followUpQuestions: ["How do you bound global overshoot across regions?", "How are policy changes applied atomically?", "How do you protect the limiter from a hot tenant?", "What differs for login, payments, and analytics endpoints?"],
    reference: {
      diagram: {
        caption: "Each gateway decides locally from a leased quota so the hot path never blocks on the global store; the coordinator redistributes leases and bounds cross-region overshoot.",
        nodes: [
          { id: "client", label: "Client", kind: "client", col: 0, row: 1 },
          { id: "gw", label: "API gateway", kind: "edge", col: 1, row: 1 },
          { id: "local", label: "Local token bucket", kind: "cache", col: 2, row: 0 },
          { id: "policy", label: "Policy cache", kind: "cache", col: 2, row: 2 },
          { id: "coord", label: "Quota coordinator", kind: "service", col: 3, row: 1 },
          { id: "store", label: "Counter store (sharded)", kind: "store", col: 4, row: 1 },
          { id: "control", label: "Policy control plane", kind: "service", col: 4, row: 2 },
          { id: "upstream", label: "Upstream service", kind: "service", col: 2, row: 3 },
        ],
        edges: [
          { from: "client", to: "gw", label: "request" },
          { from: "gw", to: "local", label: "check" },
          { from: "local", to: "coord", label: "refill", async: true },
          { from: "coord", to: "store", label: "incr" },
          { from: "gw", to: "policy", label: "rules" },
          { from: "control", to: "policy", label: "push", async: true },
          { from: "gw", to: "upstream", label: "allow" },
          { from: "control", to: "coord", label: "limits", async: true },
        ],
      },
      scope: ["Return allow/deny, remaining budget, and retry-after", "Support hierarchical limits such as tenant plus user plus endpoint", "Define maximum overshoot and behavior when the decision store is unavailable"],
      apis: ["check(key, policy_id, cost, request_id) → decision, remaining, retry_after, policy_version", "PUT /policies/{id} with version and activation time", "Optional lease(key, tokens, epoch) for local enforcement"],
      dataModel: ["Policy(id, dimensions, algorithm, rate, burst, version, activation_time, failure_mode)", "Bucket(key, policy_version, tokens_or_count, last_refill_at_authoritative, expiry)", "Lease(key, region, amount, consumed, expires_at, epoch) for bounded distributed overshoot"],
      architecture: ["Gateway derives canonical limit keys and loads versioned policy from a local cache", "Local limiter enforces leased tokens on the request path", "Partitioned regional state store performs atomic refill-and-consume when a lease is renewed", "Global allocator divides a tenant budget into bounded regional leases", "Configuration stream invalidates policy caches and moves enforcement between epochs"],
      invariants: ["A single atomic transition never consumes more tokens than available", "Policy version used for a decision is observable", "Worst-case overshoot is bounded by outstanding leases plus in-flight decisions", "Time rollback cannot create tokens", "Failure mode is explicit per protected operation"],
      deepDives: [
        { title: "Algorithm", summary: "Token bucket represents a sustained rate with bounded burst.", points: ["Refill = min(capacity, tokens + elapsed × rate); consume only if balance covers request cost. Execute atomically per key.", "Use a monotonic clock only within one process. Shared state computes nonnegative elapsed time in the atomic store’s authoritative clock domain or logical ticks, then caps at capacity.", "A sliding-window counter interpolates adjacent buckets for a cheaper approximation; a log is exact but memory-heavy."] },
        { title: "Distributed enforcement", summary: "Locality trades exactness for latency and availability.", points: ["Leasing N tokens per region bounds overshoot by the sum of unconsumed leases while removing a cross-region call per request.", "Small leases improve global accuracy but increase allocator traffic; adapt lease size to rate and risk."] },
        { title: "Overload and failure", summary: "The limiter must not become the outage amplifier.", points: ["Use per-key sharding, request coalescing for lease renewal, quotas on config/cardinality, and bounded state TTL.", "Fail closed for abuse- or money-sensitive actions; fail open with conservative local emergency budgets for availability-sensitive reads."] },
      ],
      scaling: ["Shard state by a stable hash of policy plus subject", "Keep decisions and policy reads local to the gateway region", "Use hierarchical or leased budgets for global limits", "Apply heavier approximate sketches before exact per-key state for attack traffic", "Expire inactive keys and cap tenant cardinality"],
      observability: ["Decision latency and store dependency rate", "Allow/deny counts by policy version", "Lease utilization and estimated overshoot", "Hot-key and partition skew", "Policy propagation lag", "Fail-open/closed activations and customer-visible 429 rate"],
    },
  },
];
