import type { DesignPrompt, RawStudyTopic } from "./types";

export const foundationTopics: RawStudyTopic[] = [
  {
    id: "estimation",
    week: 1,
    day: 1,
    tier: 0,
    title: "Estimation & latency intuition",
    eyebrow: "Capacity before components",
    estimatedMinutes: 75,
    summary: "Turn product scale into QPS, bytes, bandwidth, concurrency, working-set size, and accelerator demand—then connect each number to a design decision.",
    whyItMatters: "Every number you produce in a design is a claim about what breaks first. Three thousand writes a second against a 200-gigabyte working set argues for one partition count and one cache budget; the same three thousand writes against two terabytes argues for something else entirely. The arithmetic is cheap, and it is worth nothing until you name the decision it just changed.",
    objectives: ["Build dimensionally correct order-of-magnitude models", "Separate average load, peak load, skew, and failure headroom", "Translate capacity into partitions, replicas, cache, network, and compute"],
    concepts: ["Little’s Law", "Peak factor", "Working set", "Replication overhead", "Tail latency", "Usable throughput"],
    deepDive: [
      {
        title: "Model demand before fleet size",
        summary: "Start with units and a workload envelope, not server counts.",
        points: [
          "Average QPS = active users × operations per user per day ÷ 86,400. Model reads and writes separately because their storage and consistency paths differ.",
          "Peak is not a universal multiplier: consumer traffic follows time zones and events, batch traffic is scheduled, and reconnect storms correlate after failures. State the assumed peak and skew explicitly.",
          "For a stable system, Little’s Law gives average work inside a boundary: L = throughput × average total time in that boundary. Include queueing time when counting queued in-flight requests; use service time only for actively serviced work.",
        ],
      },
      {
        title: "Account for amplification",
        summary: "Logical traffic is rarely the physical work the system performs.",
        points: [
          "Do the multiplication once, explicitly. A terabyte of logical rows carrying two secondary indexes at roughly 20 percent of base size each, replicated three ways, with 30 percent compaction slack on top, provisions about 5.5 terabytes of disk. Keep the logical and physical figures on separate lines so the multiplier stays visible and arguable.",
          "Treat retention as a second, independent multiplier. Thirty daily incremental snapshots of slowly-changing data cost far less than thirty full copies, but they still occupy storage and, more importantly, the restore path has to move those bytes back inside the recovery objective you promised.",
          "A write may fan out to replicas, indexes, caches, event streams, and analytics. A feed write may additionally fan out to thousands of inboxes.",
          "Use p95 or p99 payload and sequence length for memory admission limits; the mean hides the requests most likely to exhaust a queue, heap, or KV cache.",
        ],
      },
      {
        title: "Turn estimates into thresholds",
        summary: "Every estimate should cause a decision or define a measurement to collect.",
        points: [
          "Compare the working set with effective cache capacity after replication and allocator overhead; this determines whether storage miss traffic is survivable.",
          "For accelerators, divide token demand by benchmarked throughput at the target latency and sequence mix—not peak FLOPS—and reserve headroom for failures and fragmentation.",
          "Name the sensitivity: if an unknown could change the architecture, bracket it and ask for a product measurement rather than inventing precision.",
        ],
      },
      {
        title: "Anchor the numbers to physics",
        summary: "Order-of-magnitude intuition comes from a handful of memorized reference points.",
        points: [
          "Main memory answers a lookup in roughly 100 nanoseconds, an NVMe random read in roughly 100 microseconds, and a New York-to-London round trip in roughly 70 milliseconds — spanning close to six orders of magnitude. Place each hop of your design on that scale before you argue about which one to optimize.",
          "Light in fiber travels about 200 kilometers per millisecond, so the 5,600 km between New York and London costs about 28 milliseconds one way before a single router touches the packet. That floor is what makes a synchronous cross-ocean hop an architectural commitment rather than a tuning problem.",
        ],
      },
    ],
    tradeoffs: [
      { decision: "Precision vs speed", preferA: "Use one-significant-digit estimates when choosing architecture during an interview.", preferB: "Use a more detailed model for memory fit, cost commitments, or a hard SLO.", watch: "False precision can hide uncertainty in peak factor and skew." },
      { decision: "Headroom vs utilization", preferA: "Reserve capacity for correlated failures and fast traffic growth when availability matters.", preferB: "Run hotter when work is delay-tolerant and admission can shed load safely.", watch: "Average utilization says little about tail latency near saturation." },
      { decision: "Batching vs latency", preferA: "Batch offline or throughput-bound work to amortize fixed cost.", preferB: "Use bounded or continuous batching for interactive paths with tail-latency SLOs.", watch: "Unbounded queueing can erase the throughput gain." },
    ],
    failureModes: [
      { mode: "Capacity model uses only daily average", symptom: "Predictable peak-hour saturation and rising queue time", mitigation: "Model peak, skew, retry amplification, and one-failure-domain loss." },
      { mode: "Logical bytes are treated as physical bytes", symptom: "Unexpected disk, network, or backup cost", mitigation: "Add replication, indexes, compaction headroom, and retention copies explicitly." },
      { mode: "Benchmark throughput is used without the SLO workload", symptom: "Fleet meets tokens/s but misses p99 latency or OOMs on long inputs", mitigation: "Benchmark the actual request mix and enforce admission by memory-weighted work." },
    ],
    interviewQuestions: ["Which estimate can change the architecture?", "What happens to capacity during a zone failure?", "How does key or tenant skew alter the mean?", "Which assumption would you validate first in production?"],
    decisionChecklist: ["Write units on every intermediate value", "Separate average, peak, skew, and failure load", "Separate logical data from physical amplification", "State headroom and utilization target", "Name the architectural consequence"],
    exercise: "Estimate peak QPS, storage, cache working set, and regional failover load for a URL shortener serving 100 million redirects per day with a Zipf-like hot-link distribution.",
    prerequisites: ["Basic arithmetic", "Units and powers of ten"],
    relatedDesigns: ["url-shortener", "classic-chat", "classic-observability-platform", "llm-large-scale-serving"],
    quiz: [
      { prompt: "At 20,000 requests/s and 80 ms average time inside the request-processing boundary, what is the average number of requests in that boundary?", options: ["250", "1,600", "20,080", "250,000"], answerIndex: 1, explanation: "Little’s Law: 20,000/s × 0.08 s = 1,600 requests on average inside the measured boundary. The tempting 250,000 comes from dividing by 0.08 instead of multiplying — the standard unit slip — and 20,080 comes from adding a rate to a latency, which is dimensionally meaningless." },
      { prompt: "Which quantity should a cache be sized against?", options: ["The full stored dataset on disk", "Mean object size times count", "Peak write QPS times entry TTL", "Hot working set plus overhead"], answerIndex: 3, explanation: "A cache only has to hold enough of the active working set to reach the assumed hit rate, plus replication and allocator overhead. Sizing against the full stored dataset is the usual error: it treats a cache as a second copy of the database rather than a residency budget for hot keys." },
      { prompt: "When is deliberately running the fleet at high average utilization the right call?", options: ["When the work is delay-tolerant", "When zone-loss availability matters", "When the peak factor is unmeasured", "When p99 latency is the stated SLO"], answerIndex: 0, explanation: "Headroom is what absorbs correlated failure and growth, so you can spend it only where work is delay-tolerant and admission control can shed safely. The p99 option is the misconception this module names outright: average utilization says almost nothing about tail latency near saturation." },
      { prompt: "A fleet meets its benchmarked tokens/s target but misses p99 and runs out of memory on long inputs. What did the capacity model get wrong?", options: ["It counted logical bytes only", "It assumed too few replicas", "It omitted the SLO request mix", "It used average, not peak, QPS"], answerIndex: 2, explanation: "Throughput measured on a convenient sequence mix does not transfer to the real distribution, and it is the p95/p99 long inputs that exhaust memory. The average-versus-peak answer is the tempting one, but this fleet already hits its rate target: the defect is workload shape, not arrival rate." },
    ],
    recallCards: [
      { id: "est-littles-law", prompt: "State Little's Law, the condition it requires, and the mistake people make when applying it to a request path.", answer: "For a stable system, L = throughput x average time spent inside a stated boundary. It holds only in steady state and only for the boundary you actually measured. The common mistake is mixing boundaries: counting queued in-flight requests requires the total time including queueing, whereas service time alone gives only the actively-serviced concurrency. Naming the boundary before multiplying is what makes the number mean anything." },
      { id: "est-amplification", prompt: "Given a logical write volume, list the sources of physical amplification you must add before sizing storage.", answer: "Replication factor, secondary indexes, metadata, compaction slack and space amplification, erasure-coding overhead, and retained backup or snapshot copies. Separately, a single logical write may fan out to replicas, indexes, caches, event streams, and analytics, and a feed write may fan out to thousands of inboxes. Keep logical and physical numbers on separate lines so the amplification factor stays visible and arguable." },
    ],
  },
  {
    id: "consistency-idempotency",
    week: 1,
    day: 2,
    tier: 0,
    title: "Consistency, transactions & idempotency",
    eyebrow: "Guarantees by invariant",
    estimatedMinutes: 85,
    summary: "Choose guarantees per operation, define invariants at the source of truth, and make every externally retryable effect safe under ambiguity.",
    whyItMatters: "When a payment request times out, nothing in the caller's world distinguishes a write that committed from one that never arrived, and almost every decision in this module — where the invariant is enforced, what the idempotency key is bound to, whether the lock carries a fencing token, whether the event ships through an outbox — exists to make that ambiguity survivable rather than to pretend it away.",
    objectives: ["Separate linearizability from serializability and isolation", "Apply CAP/PACELC to concrete operations", "Design idempotent writes across databases and queues"],
    concepts: ["Linearizability", "Serializability", "Snapshot isolation", "Causal consistency", "Idempotency key", "Fencing token", "Transactional outbox"],
    deepDive: [
      {
        title: "Name the guarantee precisely",
        summary: "Consistency has several independent dimensions.",
        points: [
          "Linearizability is real-time ordering of individual operations; serializability is equivalence to some serial transaction order. A database can offer serializable transactions without external real-time ordering.",
          "Snapshot isolation gives each transaction a consistent snapshot but can permit write skew unless the invariant is represented by a conflicting write or stronger isolation is used.",
          "CAP concerns behavior while a network partition exists; PACELC adds the normal-case latency-versus-consistency choice. Neither means a database is simply ‘CP’ for every operation.",
        ],
      },
      {
        title: "Make uncertain retries harmless",
        summary: "A timeout does not reveal whether the first attempt committed.",
        points: [
          "Bind the key to the caller, the operation, and a hash of the normalized payload — a record identified by something like `idem:acct_8812:POST /v1/payments:sha256(body)`, not by a client-chosen string alone. Persist that key, the payload hash, the state, and the eventual response in the same transaction as the business mutation, so the record cannot exist without the effect or the effect without the record.",
          "Make concurrent duplicates converge on one result, and reject reuse of a key whose payload hash differs instead of aliasing it to the old response. Retain the record for the longer of the retry window and the business dispute window: card disputes surface up to 90 days later, so a 24-hour retention sized to the client's retry policy discards the evidence long before anyone asks for it.",
          "Queues generally provide at-least-once delivery. Put deduplication or a unique business key at the effect boundary; exactly-once processing inside a broker does not make arbitrary external effects exactly once.",
        ],
      },
      {
        title: "Coordinate without stale owners",
        summary: "Locks need leases and fencing, not faith in process liveness.",
        points: [
          "Optimistic concurrency uses a version predicate in the write and retries a recomputation on conflict; it works well when contention is low and conflicts are safe to expose.",
          "A lease can expire while its holder is paused. A monotonically increasing fencing token (also called a fencing epoch) lets the protected resource reject writes from an old holder.",
          "Use an outbox row committed with domain state, then relay it to the stream. Consumers remain idempotent because relay publication can repeat after a crash.",
        ],
      },
    ],
    tradeoffs: [
      { decision: "Strong vs eventual reads", preferA: "Use linearizable reads when a decision requires the latest committed state; enforce uniqueness, money, and inventory with conditional writes or serializable transactions.", preferB: "Use replicas or materialized views for feeds, presence, and analytics where staleness is bounded and visible.", watch: "Read strength alone does not make a read-then-write sequence atomic." },
      { decision: "Optimistic vs pessimistic concurrency", preferA: "Prefer version checks for low contention and short mutations.", preferB: "Prefer locks or serialized ownership for hot, correctness-critical resources.", watch: "Long transactions and lock convoys destroy latency." },
      { decision: "Synchronous side effect vs outbox", preferA: "Use a single transaction when the state and effect share one transactional resource.", preferB: "Use outbox plus idempotent consumer across storage or service boundaries.", watch: "Dual writes create missing or phantom events." },
    ],
    failureModes: [
      { mode: "Client times out after commit and retries", symptom: "Duplicate charge, order, or notification", mitigation: "Atomically persist an idempotency record and return its prior result." },
      { mode: "Snapshot-isolated transactions write skew", symptom: "Cross-row invariant violated despite no write-write conflict", mitigation: "Materialize the invariant into a conflicting row, lock the predicate, or use serializable isolation." },
      { mode: "Expired lock holder keeps writing", symptom: "New owner’s work is overwritten by a paused old process", mitigation: "Issue fencing tokens and reject any write carrying a stale fencing token at the resource." },
    ],
    interviewQuestions: ["What exact invariant needs coordination?", "What does a caller do after an ambiguous timeout?", "Where is the idempotency record committed?", "Can a stale lease holder still mutate state?"],
    decisionChecklist: ["State invariants before consistency levels", "Classify each read/write path independently", "Specify retry identity and retention", "Put dedupe at the effect boundary", "Explain conflict and stale-owner handling"],
    exercise: "Specify guarantees and retry behavior for payment capture, inventory reservation, chat presence, profile updates, likes, and analytics ingestion.",
    prerequisites: ["Transactions", "Failure and timeout basics"],
    relatedDesigns: ["classic-payment-ledger", "classic-notifications", "classic-file-sync", "ads-ctr"],
    quiz: [
      { prompt: "A client times out after payment creation and retries with the same idempotency key but a different amount. What should the API do?", options: ["Create a second payment at the new amount", "Overwrite the stored request with the newer", "Reject the retry: the payload hash differs", "Return the first result and ignore the change"], answerIndex: 2, explanation: "The key identifies one logical operation bound to a payload hash, so reuse with different semantics must be rejected rather than aliased. Silently returning the original result is the tempting answer — it sounds like idempotency, but it hides a real second intent behind a stale response." },
      { prompt: "Why is a lease alone insufficient for exclusive writes?", options: ["A paused holder can resume after expiry", "Synchronized clocks make the expiry exact", "Only one owner can ever hold a lease", "A lease cannot be renewed by a holder"], answerIndex: 0, explanation: "A process can pause past its lease, then resume unaware that a new owner exists, so the resource needs a fencing token to reject it. The clock answer is the misconception: tighter clock synchronization narrows the window but never removes the pause, so mutual exclusion must be enforced at the resource." },
      { prompt: "Clients may retry a capture for up to 24 hours, and cardholder disputes arrive as late as 90 days after the charge. How long must the idempotency record be retained?", options: ["24 hours, the client retry window", "At least 90 days, to cover disputes", "Until the payment settles with the bank", "7 days, matching broker retention"], answerIndex: 1, explanation: "Retention must cover the maximum retry window and the dispute window, whichever is longer, because a replayed or re-examined operation after record expiry looks like a brand-new request. Choosing 24 hours is the common error: it sizes retention to the client's retry policy and forgets the business dispute path." },
      { prompt: "Two on-call engineers each run a transaction that checks another engineer is still on shift, then removes themselves. Both commit; the rota is now empty. No two rows conflicted. What is this?", options: ["A lost update from a stale read", "A dirty read of uncommitted state", "A phantom created by a missing index", "Write skew under snapshot isolation"], answerIndex: 3, explanation: "Each transaction read a consistent snapshot and wrote a different row, so snapshot isolation found no write-write conflict and let both commit while the cross-row invariant broke. Calling it a lost update is the classic mislabel: nothing was overwritten, so the fix is materializing the invariant into a conflicting row or using serializable isolation." },
    ],
    recallCards: [
      { id: "con-lin-vs-ser", prompt: "Distinguish linearizability from serializability, and explain why a database can offer one without the other.", answer: "Linearizability is a real-time ordering guarantee on individual operations: once a write completes, every later read observes it. Serializability is an isolation guarantee that a set of transactions is equivalent to some serial order, with no requirement that the order match real time. A database can therefore provide serializable transactions while a read issued after a commit still misses it, because nothing ties the serial order to wall-clock ordering. Strict serializability is the combination of both." },
      { id: "con-idempotency-key", prompt: "Describe what an idempotency key must be bound to, what is stored with it, and how concurrent duplicates are handled.", answer: "Bind the key to caller, operation, and a hash of the normalized payload. Atomically persist the key, payload hash, state, and the eventual response in the same transaction as the business mutation, so the record cannot exist without the effect or vice versa. Concurrent duplicates must converge on one result, typically by having the loser wait on or read the winner's record. Reuse of the key with a different payload hash must be rejected rather than aliased, and keys are retained through the maximum retry and dispute window." },
    ],
    furtherReading: [{ label: "Herlihy & Wing — Linearizability", url: "https://cs.brown.edu/~mph/HerlihyW90/p463-herlihy.pdf" }],
  },
  {
    id: "replication-partitioning",
    week: 1,
    day: 3,
    tier: 0,
    title: "Replication, consensus & partitioning",
    eyebrow: "Scale data without losing ownership",
    estimatedMinutes: 90,
    summary: "Choose a replication protocol and partition key together, then describe leadership, quorum, rebalancing, hot-key isolation, and failover explicitly.",
    whyItMatters: "“Add shards” is a capacity answer to what is usually an ownership question. A partition split is a protocol with a snapshot, a change stream, a fenced cutover and a rollback path — not a metadata edit. A quorum inequality tells you which replica sets intersect, not which value a client will read. What actually pages someone is the transition: a stale router still writing to the previous owner, a rebuild saturating the same link its neighbors are recovering over, one celebrity key that no quantity of hardware divides.",
    objectives: ["Distinguish consensus quorums from Dynamo-style quorums", "Select keys from access patterns and cardinality", "Narrate a safe reshard and regional failover"],
    concepts: ["Leader-follower", "Consensus log", "Term/epoch", "Leaderless quorum", "Consistent hashing", "Virtual node", "Hot partition", "Resharding"],
    deepDive: [
      { title: "Replication models", summary: "Replication semantics determine write ownership and conflict behavior.", points: ["In Raft, an entry from the leader’s current term becomes committed once replicated to a majority; quorum intersection plus the election log-freshness rule ensures later leaders contain committed entries.", "For fixed replica membership, R + W > N gives read/write quorum intersection, but not linearizability by itself; ordering versions and returning the latest completed write require an additional protocol. Sloppy quorums and asynchronous read repair weaken that guarantee.", "Multi-leader accepts writes in multiple sites and therefore needs deterministic conflict resolution, domain-specific merge, or user-visible conflicts. Last-write-wins can silently discard updates under clock skew.", "Paxos solves consensus on a single value through prepare/accept rounds with proposal numbers; Multi-Paxos amortizes the prepare phase across a stable leader, which is structurally what Raft prescribes with terms and an explicit log. Raft is not a different guarantee—it is the same safety made teachable by fixing leadership and log contiguity, which is why production systems built on either converge on a leader-based replicated log."] },
      { title: "Partition from access patterns", summary: "A high-cardinality key is necessary but not sufficient.", points: ["Hash partitioning spreads point traffic but loses range locality; range partitioning supports scans but concentrates sequential inserts and popular ranges.", "Co-locate data that must be transacted or read together, but avoid a tenant or celebrity key whose rate exceeds one partition’s capacity.", "Secondary indexes are local or global: local indexes scatter queries; global indexes add an asynchronously or transactionally maintained partitioned structure."] },
      { title: "Move ownership safely", summary: "Resharding is a protocol, not a metadata edit.", points: ["Treat a split as a migration with a clock running on it. A 200-gigabyte partition streamed to its new owner at 200 MB/s spends roughly 17 minutes copying before the change log even begins to drain, and for that entire window two nodes hold beliefs about the same keys. The ordered sequence this demands is spelled out in the decision checklist below.", "Clients and routers must tolerate stale maps via redirects or retries; a monotonically increasing fencing token (also called a fencing epoch, and distinct from the routing epoch above) prevents an old owner from accepting writes after cutover.", "Throttle movement to protect foreground traffic. A failed node and its replicas must not all rebuild through the same constrained network link."] },
    ],
    tradeoffs: [
      { decision: "Hash vs range partitioning", preferA: "Hash for uniform point access and elastic distribution.", preferB: "Range for ordered scans and time/range locality.", watch: "Monotonic keys and hot tenants defeat naive range layouts." },
      { decision: "Leader vs leaderless writes", preferA: "Leader for ordered mutations, simpler transactions, and strong consistency.", preferB: "Leaderless for high write availability with resolvable conflicts.", watch: "Read repair does not prevent all stale reads or lost concurrent intent." },
      { decision: "Co-location vs distribution", preferA: "Co-locate transactional aggregates and common joins.", preferB: "Distribute extremely hot entities or independently scalable subresources.", watch: "Cross-shard coordination migrates complexity into transactions and operations." },
    ],
    failureModes: [
      { mode: "Hot key exceeds a partition", symptom: "One shard saturates while fleet utilization remains low", mitigation: "Cache, split by subkey/time, isolate the tenant, or aggregate through hierarchical ownership." },
      { mode: "Stale router writes to old owner", symptom: "Lost or divergent writes during resharding", mitigation: "Use routing epochs, redirects, and fencing tokens at storage nodes." },
      { mode: "Replica rebuild saturates shared network", symptom: "Failover triggers wider latency and replication lag", mitigation: "Rate-limit repair, use diverse sources, and reserve recovery bandwidth." },
      { mode: "Partition leaves a minority still serving writes", symptom: "Two sides of the split each accept mutations and diverge, and reconciliation after the heal silently discards one side", mitigation: "Require a majority quorum to hold leadership, make the minority step down when it cannot renew, and expose the divergence rather than letting last-write-wins resolve it." },
    ],
    interviewQuestions: ["What is the partition key for each dominant query?", "Who can accept a write during leadership change?", "How is a hot tenant split?", "How do stale routers learn a new map?"],
    decisionChecklist: ["Identify write owner and commit rule", "Map every query to a partition route", "Describe conflict/version semantics", "Open a new routing epoch before any data moves", "Copy a consistent snapshot, then stream the change log behind it", "Validate replication lag and checksums before cutting over", "Cut reads and writes under the new epoch, fencing the old owner", "Retain rollback state until the previous owner is fully drained", "Test a hot key and one-zone loss"],
    exercise: "Design a key-value store’s replication and routing layers, including a live split of one hot partition without lost writes.",
    prerequisites: ["consistency-idempotency", "Hashing"],
    relatedDesigns: ["classic-newsfeed", "classic-chat", "classic-observability-platform"],
    quiz: [
      { prompt: "Why does a Raft entry committed in its leader’s current term survive leader change?", options: ["Every replica stores every entry", "Quorum intersection plus freshness", "The leader’s clock orders all entries", "The entry reached disk on commit"], answerIndex: 1, explanation: "The election quorum intersects the commit quorum, and Raft’s voting freshness rule stops a candidate missing the committed suffix from winning. The tempting answer is that every replica holds the entry: commit requires only a majority, and a minority may lag arbitrarily without endangering safety." },
      { prompt: "Which migration step closes the gap between a copied snapshot and the writes that landed while it was copying?", options: ["Raise the TTL on the routing cache", "Fail DNS over to the new shard", "Stream the change log under an epoch", "Take a second snapshot after the copy"], answerIndex: 2, explanation: "A snapshot plus an ordered change stream brings the destination current before a fenced cutover. Taking a second snapshot is the seductive wrong answer: while writes continue, every snapshot is stale the moment it finishes, so only a continuous log can converge." },
      { prompt: "One shard sits at 100% while fleet-wide utilization is near 30%, and the traffic is concentrated on a single key. Which fix addresses the cause?", options: ["Add more shards to the cluster", "Raise the replication factor", "Switch reads to leaderless quorum", "Split the key by subkey or time"], answerIndex: 3, explanation: "A single key cannot be spread by adding capacity, so you must decompose it — subkey or time splitting, caching, tenant isolation, or hierarchical aggregation. Adding shards is the reflex answer and the diagnostic error: rehashing moves whole keys between shards and leaves this one indivisible." },
      { prompt: "Writes arrive keyed by timestamp and the dominant query is a time-range scan. Which layout fits, and what does it cost?", options: ["Range layout; recent inserts pile up", "Hash layout; range scans still work fine", "Range layout; hot tenants vanish", "Hash layout; ordering is retained"], answerIndex: 0, explanation: "Range partitioning is what makes an ordered scan cheap, and its price is that sequential inserts and popular ranges concentrate on one partition. Believing a hash layout keeps range scans is the misconception: hashing destroys the locality a scan depends on, turning it into a scatter across every partition." },
    ],
    recallCards: [
      { id: "rep-raft-commit", prompt: "State Raft's commit rule precisely and explain why the current-term qualifier matters.", answer: "An entry from the leader's current term is committed once it is replicated to a majority; entries from earlier terms are committed only indirectly, once an entry of the current term commits above them. The qualifier matters because a majority-replicated entry from a previous term can still be overwritten by a later leader, which is the figure-8 scenario Raft explicitly rules out. Safety comes from quorum intersection plus the election rule that a candidate missing committed entries cannot win." },
      { id: "rep-quorum-limit", prompt: "Explain what R + W > N does and does not guarantee.", answer: "With fixed replica membership it guarantees that read and write quorums intersect, so a read set contains at least one replica that saw the latest completed write. It does not by itself give linearizability: you additionally need version ordering and a rule for returning the latest completed write, and concurrent writes can still produce siblings. Sloppy quorums with hinted handoff and asynchronous read repair weaken the intersection property further, so the inequality alone is not a consistency guarantee." },
    ],
    furtherReading: [{ label: "Raft consensus paper", url: "https://raft.github.io/raft.pdf" }, { label: "Dynamo paper", url: "https://www.allthingsdistributed.com/files/amazon-dynamo-sosp2007.pdf" }],
  },
  {
    id: "networking",
    week: 1,
    day: 4,
    tier: 0,
    title: "Networking & service boundaries",
    eyebrow: "Trace every request hop",
    estimatedMinutes: 80,
    summary: "Explain the end-to-end request path and make protocols, load balancing, connection management, deadlines, retries, and backpressure part of the design.",
    whyItMatters: "A service can hold every CPU under 40 percent and still time out, because the queue that filled was a connection pool, the deadline that expired belonged to a caller three hops upstream, and the load that arrived was its own retries compounding. None of that is visible in the metrics anyone looks at first, which is why the request path has to be walked hop by hop instead of drawn as a single arrow.",
    objectives: ["Choose request, stream, and peer-to-peer protocols by semantics", "Budget deadlines and retries across hops", "Design connection and load-balancing behavior under failure"],
    concepts: ["TCP flow control", "HTTP/2 multiplexing", "gRPC deadline", "L4/L7 balancing", "Connection pool", "Retry budget", "Circuit breaker", "CDN"],
    deepDive: [
      { title: "Select transport from interaction shape", summary: "Protocol choice follows delivery, fan-out, browser, and latency needs.", points: ["HTTP request/response is operationally simple; gRPC adds typed contracts, streaming, and efficient binary framing for controlled clients; neither removes application-level compatibility.", "WebSockets provide a bidirectional, ordered message channel over a long-lived TCP connection and require gateway ownership plus reconnect/resume logic. WebRTC adds NAT traversal and media-oriented peer paths, usually with signaling and relay fallback.", "TCP guarantees ordered delivery, so one lost packet can delay later bytes on that connection. HTTP/2 multiplexes application streams but still shares the TCP loss domain."] },
      { title: "Propagate one end-to-end deadline", summary: "Independent per-hop timeouts create work after the caller has left.", points: ["The edge sets a deadline; each hop subtracts elapsed and reserve time. Downstream work should cancel when the deadline expires.", "Retry only transient, safe operations with exponential backoff, jitter, a maximum attempt count, and a fleet-wide retry budget. Hedging is reserved for idempotent tail-sensitive reads.", "Make overload explicit with bounded queues, concurrency limits, and retryable rejection. A circuit breaker cannot create capacity; it prevents repeated expensive failures."] },
      { title: "Operate connection-heavy systems", summary: "Connections are state and must be distributed deliberately.", points: ["Load balancing differs for short requests and long-lived sessions. Gateways register session ownership so a message router can find the connection without global broadcast.", "A pool bounds concurrency, which means it is also a queue. Fifty connections in front of a dependency with a 40-millisecond service time sustain about 1,250 requests per second and not one more; past that, callers block acquiring a connection, and the wait appears in neither wire latency nor dependency CPU. Instrument pool wait time, active and idle counts, handshake rate, resets, and ephemeral-port pressure as first-class signals rather than as debug counters.", "Reconnects after a regional or network event must use server hints and randomized client backoff; otherwise recovery traffic can exceed steady-state traffic by orders of magnitude."] },
      { title: "Pay for the connection before the request", summary: "Setup cost dominates short interactions on long paths.", points: ["A cold HTTPS request buys three round trips before any application byte moves: a DNS resolution, a TCP handshake, and a TLS 1.3 handshake. At a 70-millisecond cross-continent round trip that is roughly 210 milliseconds of setup wrapped around work that may take five.", "Terminating TLS at an edge point of presence 10 milliseconds from the user collapses those three round trips to about 30 milliseconds and leaves one warm pooled hop to origin. Connection reuse, session resumption, and keeping pools warm are latency features, not housekeeping."] },
    ],
    tradeoffs: [
      { decision: "REST/JSON vs RPC/Protobuf", preferA: "REST/JSON for public, cacheable, human-debuggable interfaces.", preferB: "Typed RPC for high-volume internal contracts and streaming.", watch: "Schema evolution and deadline semantics matter more than encoding alone." },
      { decision: "L4 vs L7 load balancing", preferA: "L4 for low overhead and protocol transparency.", preferB: "L7 for request-aware routing, auth, retries, and observability.", watch: "L7 retries can multiply application retries." },
      { decision: "Persistent vs short connections", preferA: "Persistent for frequent interaction and server push.", preferB: "Short-lived stateless requests for simpler mobility and load balancing.", watch: "Idle memory, heartbeats, ownership, and reconnect storms." },
      { decision: "Proxy vs client-side load balancing", preferA: "Route through a proxy or sidecar when policy, retries, and telemetry must be uniform across many languages.", preferB: "Let clients pick endpoints directly when one extra hop of latency and one more failure domain are not worth the central control.", watch: "Client-side balancing pushes routing, health checking, and outlier ejection into every runtime, so the oldest client library becomes the policy floor." },
    ],
    failureModes: [
      { mode: "Nested retries amplify load", symptom: "Dependency slowdown causes traffic to multiply at every layer", mitigation: "Choose one retry owner, propagate deadlines, and enforce a retry budget." },
      { mode: "Pool exhaustion hides as service latency", symptom: "Requests wait before any network call while dependency CPU looks normal", mitigation: "Bound concurrency and instrument pool wait separately from wire latency." },
      { mode: "Reconnect storm after gateway loss", symptom: "Recovery repeatedly overloads authentication and session stores", mitigation: "Use jittered exponential reconnect, admission control, and session-resume tokens." },
    ],
    interviewQuestions: ["Where does the end-to-end deadline originate?", "Which layer owns retries?", "How does a router find a user’s live connection?", "What protects the service during reconnect?"],
    decisionChecklist: ["Draw DNS/TLS/edge/load-balancer hops", "Classify interaction as request, stream, or media", "Propagate deadlines and cancellation", "Bound pools, queues, and retries", "Describe reconnection and backpressure"],
    exercise: "Trace video playback, chat delivery, and an internal RPC from client to source of truth, including timeout and overload behavior at each hop.",
    prerequisites: ["TCP/IP basics", "Client-server model"],
    relatedDesigns: ["classic-chat", "classic-notifications", "llm-multi-model-gateway"],
    quiz: [
      { prompt: "A three-hop call stack allows three total attempts at every hop. Roughly how many leaf attempts can one request create?", options: ["3", "9", "27", "81"], answerIndex: 2, explanation: "Independent attempt budgets multiply: 3 × 3 × 3 = 27 leaf attempts, so centralize retry ownership and budget it fleet-wide. Answering 9 encodes the common mental model that per-hop budgets add up (3 + 3 + 3) rather than compound, and 3 assumes one global budget that no layer is actually enforcing." },
      { prompt: "What is the safest response to overload for nonessential work?", options: ["Queue the excess until capacity is freed", "Retry the failed request immediately", "Shed load early with bounded admission", "Open a breaker to add back capacity"], answerIndex: 2, explanation: "Bounded admission with retryable rejection preserves useful work and prevents queueing collapse, and clients should retry only with a budget and jitter. The circuit-breaker option encodes the misconception this module corrects directly: a breaker stops repeated expensive failures, but it cannot create capacity." },
      { prompt: "What does one end-to-end deadline give you that independent per-hop timeouts do not?", options: ["A bounded total plus cancellation", "The sum of every hop’s timeout", "A guarantee no hop ever expires", "A retry budget for every service hop"], answerIndex: 0, explanation: "The edge sets one deadline, each hop subtracts elapsed and reserve time, and downstream work cancels once it expires, so the worst case is bounded and no capacity is spent on results nobody will read. Believing the total is the sum of per-hop timeouts describes precisely the failure mode deadlines exist to remove." },
      { prompt: "Requests wait a long time before any network call is even issued, yet the dependency’s CPU and measured wire latency both look normal. What is the likeliest cause?", options: ["The dependency is CPU-saturated", "The connection pool is a hidden queue", "TCP head-of-line blocking on packet loss", "An L7 balancer is adding retries"], answerIndex: 1, explanation: "A bounded pool becomes an invisible queue: callers block acquiring a connection, so the wait never appears in wire latency and the dependency looks healthy. Blaming dependency CPU is the standard misdiagnosis — instrument pool wait time, active/idle counts, and handshake rate separately from wire latency." },
    ],
    recallCards: [
      { id: "net-deadline", prompt: "Explain end-to-end deadline propagation and why independent per-hop timeouts are worse.", answer: "The edge sets one deadline for the whole request; each hop subtracts elapsed time plus a reserve before calling downstream, and cancels work when the deadline passes. Independent per-hop timeouts let a downstream hop keep working long after the caller has given up, burning capacity on results nobody will read, and they make the worst-case total the sum of every hop's timeout rather than a bounded budget." },
      { id: "net-retry-amplify", prompt: "Show how retries amplify across layers and state the mitigations.", answer: "Independent attempt budgets multiply: three hops each allowing three attempts yields up to 27 leaf attempts from one request, so a slow dependency sees load multiply exactly when it is least able to absorb it. Mitigate by choosing a single retry owner rather than retrying at every layer, enforcing a fleet-wide retry budget as a fraction of traffic, using exponential backoff with jitter, and propagating deadlines so a doomed request stops early." },
    ],
    furtherReading: [{ label: "HTTP/2 specification (RFC 9113)", url: "https://www.rfc-editor.org/rfc/rfc9113" }],
  },
  {
    id: "caching-queues",
    week: 2,
    day: 1,
    tier: 0,
    title: "Caching, logs & backpressure",
    eyebrow: "Control repeated and deferred work",
    estimatedMinutes: 90,
    summary: "Use caches to remove repeated work and queues or logs to decouple producers, while preserving freshness, ordering, retry safety, and bounded resource use.",
    whyItMatters: "A cache and a queue both work by letting two copies of the truth disagree for a while. That is the entire benefit — repeated reads stop reaching the origin, slow consumers stop blocking producers — and it is also the entire cost, collected later as a late fill overwriting a newer value, a poison record parked at the head of a partition, or a backlog whose retention outlives the disk it sits on. Writing down the freshness bound and the lag bound is what turns that disagreement from an accident into a contract.",
    objectives: ["Choose a cache ownership and invalidation model", "Distinguish task queues from partitioned durable logs", "Design idempotent consumers and end-to-end backpressure"],
    concepts: ["Cache-aside", "Write-through", "Request coalescing", "Partitioned log", "Consumer group", "At-least-once", "Dead-letter", "Backpressure"],
    deepDive: [
      { title: "Treat cache entries as derived state", summary: "Freshness is a contract, not merely a TTL.", points: ["Cache-aside reads source on miss and populates; concurrent misses need request coalescing or probabilistic early refresh to avoid a stampede.", "Invalidation should carry a version when reordering is possible. A late invalidation or old fill must not overwrite a newer cached value.", "Negative caching protects repeated misses but needs shorter TTLs and invalidation on creation. Hot keys may require replication, local near-caches, or request collapsing.", "Reason about the miss rate, not the hit rate. At 100,000 reads per second a 99 percent hit rate forwards 1,000 requests to the origin and a 98 percent hit rate forwards 2,000 — the one-point slip that looks like rounding error on a dashboard is a doubling of everything the origin has to survive."] },
      { title: "Choose queue or log by consumption semantics", summary: "Work distribution and event history are different abstractions.", points: ["A task queue transfers ownership of work and often deletes after acknowledgment (RabbitMQ, SQS). A durable partitioned log retains ordered records and lets independent consumer groups track offsets and replay (Kafka, Pulsar, Kinesis). Name the semantics you need before naming the product.", "Ordering is normally per partition, not global. The partition key must match the entity whose events need order; more partitions improve parallelism but weaken ordering scope.", "Acknowledgment after side effect avoids loss but permits duplicate delivery after a crash. The consumer must make the effect idempotent before advancing its durable position."] },
      { title: "Backpressure spans the entire path", summary: "A broker defers overload; it does not remove it.", points: ["Track lag in time, not only in message count: a consumer 400,000 records behind on a topic moving 20,000 records per second is 20 seconds behind, and whether 20 seconds is fine or fatal depends entirely on what the records are. Decide in advance the age at which a unit of work becomes too stale to execute, rather than discovering that threshold during an incident.", "A retry topic delays a failed record and lets the main partition advance, but sacrifices strict per-key order unless later records are sequence-gated or the partition remains paused. Poison records still need owned quarantine and safe replay.", "Producers need admission, quotas, or degradation when consumers cannot catch up. Otherwise retained backlog eventually exhausts disk and recovery time." ] },
    ],
    tradeoffs: [
      { decision: "TTL vs event invalidation", preferA: "TTL for simple bounded staleness and resilience to missed events.", preferB: "Versioned invalidation for tighter freshness on mutable hot data.", watch: "Use both when invalidation delivery is not perfect." },
      { decision: "Queue vs durable log", preferA: "Queue for competing workers and one logical processing path.", preferB: "Log for replay, audit, ordered state propagation, and multiple consumers.", watch: "Retention and per-key ordering requirements drive the choice." },
      { decision: "Strict ordering vs throughput", preferA: "One partition per ordered entity when transitions depend on sequence.", preferB: "Spread independent work across partitions for scale.", watch: "A global partition becomes a throughput and availability bottleneck." },
    ],
    failureModes: [
      { mode: "Cache stampede on expiry", symptom: "Source traffic spikes exactly at TTL boundaries", mitigation: "Use jittered expiry, request coalescing, soft TTL, and stale-if-error." },
      { mode: "Poison event blocks ordered partition", symptom: "Lag grows behind one repeatedly failing record", mitigation: "Bound attempts, quarantine with metadata, and preserve a controlled replay path." },
      { mode: "Duplicate delivery repeats side effect", symptom: "Double charge or duplicate notification after consumer crash", mitigation: "Use an idempotency/business key atomically at the effect boundary." },
    ],
    interviewQuestions: ["What is authoritative when cache and source disagree?", "Which key requires ordering?", "When is stale work discarded?", "How is a quarantined event repaired and replayed?"],
    decisionChecklist: ["Define source of truth and freshness bound", "Choose fill, invalidation, and stampede policy", "State delivery and ordering scope", "Make effects idempotent", "Bound lag, retries, and queue size"],
    exercise: "Design the event and cache paths for a payment status page where updates may be duplicated, delayed, or delivered out of order.",
    prerequisites: ["consistency-idempotency", "replication-partitioning"],
    relatedDesigns: ["classic-notifications", "classic-payment-ledger", "classic-newsfeed", "classic-observability-platform"],
    quiz: [
      { prompt: "A consumer writes to a database and crashes before acknowledging. What must the design expect?", options: ["The event is dropped by the broker", "The broker rolls back the database", "The event will be delivered again", "The offset advances despite the crash"], answerIndex: 2, explanation: "The acknowledgment never persisted, so an at-least-once broker redelivers and the database effect must be idempotent at the effect boundary. Expecting the broker to roll back the database is the tempting error: the broker has no visibility into an external write, so no transaction spans both." },
      { prompt: "What should determine a stream partition key?", options: ["The entity that needs ordering", "The current consumer group size", "A random value for even spread", "The event’s production timestamp"], answerIndex: 0, explanation: "Ordering is per partition, not global, so the key must be the entity whose state transitions depend on sequence; independent entities then parallelize freely. Choosing a random value for even spread is the misconception: it maximizes balance and destroys the only ordering guarantee the log offers." },
      { prompt: "Origin traffic spikes in sharp bursts that land exactly on TTL boundaries. What is happening, and what fixes it?", options: ["Cold cache; raise the memory limit", "Stampede; jitter expiry and coalesce", "Poison record; quarantine and replay", "Consumer lag; add more partitions"], answerIndex: 1, explanation: "Keys that were filled together expire together, so every concurrent request misses at once and hits the origin far harder than steady state; jittered or probabilistic early expiry, request coalescing, and stale-if-error break the lockstep. Reading it as a cold cache is the misdiagnosis — more memory does not stop synchronized expiry." },
      { prompt: "Routing a repeatedly failing record to a retry topic lets the main partition advance again. What does that buy back at what cost?", options: ["Delivery becomes at-most-once", "The consumer group loses its offsets", "Main-topic replay stops working", "Strict per-key ordering is given up"], answerIndex: 3, explanation: "Deferring the bad record unblocks the partition, but that record is now reprocessed after later records for the same key, so per-key order holds only if you sequence-gate the successors or keep the partition paused. Assuming delivery weakens to at-most-once is the confusion: redelivery still happens, so the consumer stays idempotent." },
    ],
    recallCards: [
      { id: "cache-stampede", prompt: "Describe what happens when a hot key expires under load and the mitigations.", answer: "Every concurrent request misses simultaneously and stampedes the origin, which can be far more load than steady state and can cascade into a full outage. Mitigate with request coalescing so one filler populates the entry while others wait, probabilistic or jittered early expiry so keys do not expire in lockstep, serving stale while revalidating in the background, and admission limits on origin fills. The cache must also be sized against the hot working set, not the whole dataset." },
      { id: "cache-queue-vs-log", prompt: "Contrast a task queue with a durable partitioned log by consumption semantics.", answer: "A task queue transfers ownership of a unit of work and typically deletes it after acknowledgment, so there is one logical consumer and no history. A durable partitioned log retains an ordered sequence and lets independent consumer groups track their own offsets and replay from any point, which is what enables adding a new consumer or reprocessing after a bug. Ordering in a log is per partition, not global, so the partition key must match the entity whose events require order." },
    ],
  },
  {
    id: "storage-indexing",
    week: 2,
    day: 2,
    tier: 0,
    title: "Storage engines & indexing",
    eyebrow: "Access patterns choose the database",
    estimatedMinutes: 95,
    summary: "Derive the data model, primary key, indexes, partitioning, retention, and engine shape from access patterns and correctness—not a product name.",
    whyItMatters: "Picking a database by name settles nothing, because two engines wearing the same label can differ by an order of magnitude on the exact write path this workload depends on. What decides the design is physical: how a write reaches durable bytes, what each index costs on every insert, when compaction starts competing with reads, and how many derived copies a deletion has to chase.",
    objectives: ["Map workload shape to relational, KV, wide-column, object, search, vector, or analytical storage", "Compare B-tree and LSM write/read paths", "Budget secondary indexes, retention, and compaction"],
    concepts: ["Primary key", "Covering index", "B+ tree", "Write-ahead log", "Memtable", "SSTable", "Compaction", "Bloom filter", "Columnar storage"],
    deepDive: [
      { title: "Select from query and mutation shape", summary: "Begin with authoritative entities and dominant access paths.", points: ["Relational storage fits transactional invariants and indexed joins; key-value or wide-column storage fits predictable partition-key access at large scale; object storage fits immutable large blobs.", "Search indexes and vector indexes are derived serving structures, not usually the system of record. Rebuild them from versioned source data and an ordered change stream.", "Columnar analytical stores minimize scans through projection and compression; mixing long scans with latency-sensitive transactions causes resource interference."] },
      { title: "Understand the physical write path", summary: "B-trees and LSM trees move cost to different phases.", points: ["A conventional WAL-based B+ tree updates sorted pages in place, serving point/range reads predictably but causing random I/O and page splits under writes; copy-on-write variants move the durability cost differently.", "An LSM tree appends to a log and memtable, flushes immutable sorted runs, then compacts them. It trades high write throughput for read and space amplification plus background I/O.", "Bloom filters rule out absent keys probabilistically, so a negative answer lets the reader skip an entire run while a positive answer proves nothing and still costs the read. Ten bits per key is the usual operating point: about 1.25 megabytes of memory per million keys, buying roughly a one percent false-positive rate."] },
      { title: "Treat indexes as derived views", summary: "Each index improves one query by taxing writes, storage, and consistency.", points: ["A composite index follows its leading columns; order fields by equality/range and sort requirements, not by schema aesthetics.", "A global secondary index must be partitioned and maintained. If asynchronous, queries need defined lag and repair; if transactional, writes pay coordination.", "A tombstone hides a row from reads long before anything erases it, and each downstream copy learns on its own schedule — compaction when it next rewrites the file, a snapshot never, a 35-day backup rotation five weeks later. Write down the date the bytes actually disappear from each sink, because 'deleted' in the primary and 'deleted' in a backup are different dates.", "A regulatory erasure request (GDPR right to erasure, CCPA deletion) has to be chased through every derived copy rather than issued once at the primary. Track it as a durable request record carrying a per-sink completion flag — cache, search index, warehouse, embedding store, backup, log — and where a backup physically cannot be rewritten, crypto-shred instead by destroying the per-subject key." ] },
    ],
    tradeoffs: [
      { decision: "Relational vs non-relational", preferA: "Choose relational when the workload needs multi-row transactions, evolving ad-hoc queries, joins, and declarative constraints enforced by the engine.", preferB: "Choose a non-relational engine when one dominant access pattern, horizontal write scale, or a flexible/sparse shape outweighs those guarantees.", watch: "“SQL vs NoSQL” is not a decision—name the access pattern, the invariant, and the scale that force the choice, since managed relational engines now shard and non-relational engines now offer transactions." },
      { decision: "B-tree vs LSM", preferA: "B-tree for predictable point/range reads and moderate writes.", preferB: "LSM for sustained write throughput and sequential I/O.", watch: "Compaction can produce latency cliffs and temporary space amplification." },
      { decision: "Normalized vs denormalized", preferA: "Normalize authoritative transactional data and evolving relations.", preferB: "Denormalize stable serving views for bounded read latency.", watch: "Every copy needs freshness, repair, and deletion semantics." },
      { decision: "Synchronous vs asynchronous secondary index", preferA: "Synchronous when a query participates in a correctness invariant.", preferB: "Asynchronous for scalable discovery/search with explicit lag.", watch: "Do not read an async index to enforce uniqueness." },
    ],
    failureModes: [
      { mode: "Unbounded secondary-index fan-out", symptom: "Write latency and storage rise faster than source records", mitigation: "Keep only query-justified indexes and move exploratory queries to analytical/search views." },
      { mode: "Compaction competes with foreground I/O", symptom: "Periodic p99 spikes and growing space amplification", mitigation: "Throttle and schedule compaction, isolate resources, and alert on debt." },
      { mode: "Derived index accepted as source of truth", symptom: "Missing or stale documents cause irreversible decisions", mitigation: "Retain an authoritative store and reconcile versioned derived indexes." },
    ],
    interviewQuestions: ["List the exact read and write queries.", "Which field is the partition key and why?", "How stale may each index be?", "What happens to latency during compaction or backfill?"],
    decisionChecklist: ["Declare authoritative and derived stores", "Write key and index shapes for each query", "Estimate index and replication amplification", "Explain engine read/write paths", "Define retention, backfill, and repair"],
    exercise: "Choose and justify storage, keys, and indexes for a ledger, chat history, file blobs, high-cardinality metrics, embeddings, and a document search corpus.",
    prerequisites: ["replication-partitioning", "Access-pattern analysis"],
    relatedDesigns: ["classic-payment-ledger", "classic-chat", "classic-file-sync", "classic-crawler-search", "llm-enterprise-rag"],
    quiz: [
      { prompt: "What does an LSM Bloom filter actually tell the reader about a run?", options: ["Present means the key is there", "Absent means the key is not there", "It names the run holding the key", "It returns the newest value found"], answerIndex: 1, explanation: "A correctly built Bloom filter has false positives but no false negatives, so only the negative answer is trustworthy and it lets the reader skip that run entirely. Treating a positive as proof of presence is the classic error: it still requires reading the run, and often finds nothing." },
      { prompt: "Why should an asynchronously maintained search index not enforce username uniqueness?", options: ["Search cannot index exact strings", "A global index cannot be partitioned", "Uniqueness needs a covering index", "Async lag lets a duplicate commit"], answerIndex: 3, explanation: "An eventually updated index can miss a name created moments ago, so two concurrent signups both see no match and both succeed; the invariant belongs in a conditional write or transaction at the source of truth. Believing a global secondary index cannot be partitioned is the misconception — it can, but it is still derived and still lags." },
      { prompt: "A write-heavy time-series ingest path picks an LSM engine. Which cost must the design explicitly plan for?", options: ["Compaction competing with reads", "Random page splits on insert", "Loss of durability after a crash", "No support for ordered scans"], answerIndex: 0, explanation: "An LSM buys sequential write throughput and pays in read and space amplification plus background compaction that produces periodic p99 cliffs, so compaction needs throttling, scheduling, and a debt alert. Naming page splits is the swapped mental model: splits are the B-tree in-place write cost, not the LSM's." },
      { prompt: "A user’s row was deleted months ago, yet an audit still turns up their data. Which explanation matches this module?", options: ["The delete never reached the WAL", "The primary key was not indexed", "Tombstones leave derived copies", "Compaction rewrote the stale page"], answerIndex: 2, explanation: "A tombstone only makes reads skip the row; the bytes survive until compaction rewrites the files, and derived sinks — caches, search indexes, warehouses, embeddings, backups, logs — were never told at all. Blaming compaction inverts the mechanism: compaction is what finally erases, so its absence is the delay, not the leak." },
    ],
    recallCards: [
      { id: "store-btree-lsm", prompt: "Compare B-tree and LSM read/write paths and their characteristic operational risk.", answer: "A B-tree updates pages in place, giving predictable point and range reads and bounded read amplification, but random write I/O and page-level write amplification. An LSM buffers writes in memory and flushes sorted runs, giving high sequential write throughput at the cost of read amplification across levels, mitigated by bloom filters. The LSM's characteristic risk is compaction: it competes with foreground I/O and produces periodic latency cliffs and temporary space amplification." },
      { id: "store-erasure", prompt: "Explain why a tombstone is not erasure and what a regulatory deletion request must reach.", answer: "A tombstone marks a row logically deleted so reads skip it, but the bytes persist until compaction rewrites the affected files, and they may still exist in snapshots and backups. A regulatory erasure request must therefore reach every derived copy: caches, search indexes, analytical warehouses, embeddings, backups, and logs. Track it as a durable request record with per-sink completion, and where a backup cannot be rewritten, crypto-shred by destroying a per-subject key." },
    ],
    furtherReading: [{ label: "The Log-Structured Merge-Tree paper", url: "https://www.cs.umb.edu/~poneil/lsmtree.pdf" }, { label: "Bigtable paper", url: "https://static.googleusercontent.com/media/research.google.com/en//archive/bigtable-osdi06.pdf" }],
  },
  {
    id: "timed-designs",
    week: 2,
    day: 4,
    tier: 0,
    title: "Timed design execution",
    eyebrow: "Turn knowledge into a 45-minute argument",
    estimatedMinutes: 100,
    summary: "Drive a consistent interview structure, make assumptions visible, choose one valuable deep dive, and close with failure behavior and evolution.",
    whyItMatters: "Forty-five minutes is not enough time to say everything you know, and attempting it is the single most common way the hour is lost. The clock is the real design constraint: about twenty minutes to a standing end-to-end flow, fifteen to twenty on the one mechanism carrying the most risk, five to close on failure behavior and evolution. Choosing what to leave out is itself the thing being read. An interviewer can only evaluate a trade-off you actually committed to.",
    objectives: ["Reach an end-to-end architecture by minute 20", "Select a deep dive from the hardest requirement", "Narrate trade-offs, degradation, and 10× evolution"],
    concepts: ["Requirements envelope", "Critical path", "Source of truth", "Invariant", "Deep dive", "Failure injection", "Two-minute close"],
    deepDive: [
      { title: "Control the first fifteen minutes", summary: "Align scope before drawing a fleet.", points: ["Spend the opening minutes agreeing what the system is for: who uses it, which two or three operations dominate its traffic, what the latency and availability targets are, and what you are explicitly not building. Say the agreed scope back before you draw anything, because a design that answers an unshared problem cannot be rescued later.", "Budget the clock out loud — roughly 3 to 5 minutes clarifying, 3 to 5 estimating, 3 to 5 on APIs and the authoritative data model, 5 to 7 standing up the end-to-end architecture, 15 to 20 on the deep dive, and about 5 to close. Estimate only the dimensions that could change the architecture; the rest is arithmetic nobody is scoring.", "Draw the critical request path first. Add asynchronous and analytical paths only after the source-of-truth flow is coherent."] },
      { title: "Earn the deep dive", summary: "Choose depth from the design’s dominant risk.", points: ["Let the domain choose the depth for you: a payments design earns its deep dive on idempotency and ledger invariants, a feed on fan-out and hot users, an ML system on label generation and serving skew, an LLM system on memory and scheduling.", "State two options, the requirement that differentiates them, and the cost of the choice. Avoid presenting a tool as the rationale.", "Inject a failure into your own design while you are still explaining it — the client that timed out after the commit landed, the duplicate event, the zone that vanished. Say what the user observes in each case and what the system does about it without a human."] },
      { title: "Close like an owner", summary: "Summarize guarantees and the next bottleneck.", points: ["Restate the main flow, source of truth, and one deliberate trade-off. Name what is strongly consistent and what is derived.", "Give concrete SLIs, an overload mode, and recovery or rollback behavior.", "At 10×, identify the first constrained resource and the measurement that would trigger the next architecture change." ] },
    ],
    tradeoffs: [
      { decision: "Breadth vs depth", preferA: "Cover the end-to-end path and all correctness boundaries first.", preferB: "Spend remaining time on the requirement with the highest technical risk.", watch: "Premature depth can leave the system incomplete." },
      { decision: "Assumption vs clarification", preferA: "Assume a reversible detail after stating it.", preferB: "Clarify scale, invariants, and SLOs that change architecture.", watch: "Do not burn time asking low-impact product questions." },
      { decision: "Current design vs future scale", preferA: "Build the simplest design meeting the stated envelope.", preferB: "Describe an evolution trigger for plausible 10× growth.", watch: "Prebuilding hypothetical scale obscures the core design." },
    ],
    failureModes: [
      { mode: "Component list without data flow", symptom: "Diagram sounds plausible but writes, reads, and ownership are ambiguous", mitigation: "Walk one request and one state transition end to end." },
      { mode: "No explicit invariant or SLO", symptom: "Trade-offs cannot be evaluated", mitigation: "Write the correctness and user-visible targets before selecting mechanisms." },
      { mode: "No reliability close", symptom: "Happy path consumes the full interview", mitigation: "Reserve five minutes and use a standard failure/observability/evolution checklist." },
    ],
    interviewQuestions: ["What is the single hardest requirement?", "Which component owns authoritative state?", "What breaks first at 10×?", "What would the user observe during regional failure?"],
    decisionChecklist: ["Timebox six interview phases", "State scope and assumptions", "Walk the critical path", "Deep-dive one differentiating mechanism", "Close with SLOs, failure, cost, and evolution"],
    exercise: "Complete the URL shortener and distributed rate limiter in 40–45 minutes each, recording only the three mistakes that would most improve the next attempt.",
    prerequisites: ["estimation", "consistency-idempotency", "replication-partitioning", "networking"],
    relatedDesigns: ["url-shortener", "distributed-rate-limiter"],
    quiz: [
      { prompt: "By roughly what point should a 45-minute answer have an end-to-end architecture standing?", options: ["Around minute 5, before scoping", "Around minute 20, after scoping", "Around minute 40, at the close", "Only once estimates are exact"], answerIndex: 1, explanation: "A coherent high-level flow near minute 20 leaves the 15-20 minutes of deep dive and the five-minute reliability close that actually produce senior signal. Drawing the architecture by minute 5 is the tempting error: it skips scope and estimates, so the design answers a problem nobody agreed on." },
      { prompt: "What makes a trade-off explanation read as senior rather than encyclopedic?", options: ["Name the newest managed product", "List both options without choosing", "Tie a requirement to a choice and cost", "Defer the decision back to the interviewer"], answerIndex: 2, explanation: "The signal is the causal link: two viable options, the specific requirement that discriminates between them, a commitment, and what the commitment costs. Listing both options without choosing is the most common miss — it demonstrates recall of the menu while withholding the judgment being assessed." },
      { prompt: "Which requirement should you draw the deep dive from?", options: ["The one with the highest risk", "The one you have practiced most", "The one using newest technology", "The one mentioned most recently"], answerIndex: 0, explanation: "Depth is earned by going where the design is most likely to break — idempotency for payments, fan-out and hot users for feeds, memory and scheduling for LLM serving — because that is where a differentiating argument exists. Diving into your best-rehearsed area is the trap: it is comfortable and it demonstrates nothing about this problem." },
      { prompt: "Your diagram names every component, but the interviewer keeps asking who owns the write. What is missing?", options: ["A more detailed capacity model", "More components on the diagram", "A longer list of technologies", "One request traced end to end"], answerIndex: 3, explanation: "A component list is not a data flow: until you walk a single request and a single state transition from client to source of truth and back, ownership, reads, and writes stay ambiguous. Adding components is the instinctive response and makes it worse, because it multiplies the boxes whose responsibilities are undefined." },
    ],
    recallCards: [
      { id: "timed-clock", prompt: "Give the phase budget for a 45-minute design and the checkpoint that tells you that you are behind.", answer: "Roughly: clarify 3-5 minutes, estimate 3-5, APIs and data model 3-5, end-to-end architecture 5-7, deep dive 15-20, and reliability close about 5. The checkpoint is having a coherent end-to-end flow by roughly minute 20; if the high-level architecture is not standing by then, the deep dive and the reliability close will both be sacrificed, which are exactly the parts that produce senior signal." },
      { id: "timed-tradeoff", prompt: "State what makes a trade-off answer read as senior rather than encyclopedic.", answer: "Name two viable options, identify the specific requirement that discriminates between them, commit to a choice, and state what the choice costs and under what measurement you would revisit it. Listing both options without deciding reads as indecision; naming a product as the rationale reads as pattern matching. The interviewer is looking for the causal link from a stated requirement to a decision and its consequence." },
    ],
  },
  {
    id: "auth-identity-access",
    week: 2,
    day: 3,
    tier: 0,
    title: "Identity, sessions & access control",
    eyebrow: "Prove who, then decide what",
    estimatedMinutes: 80,
    summary: "Separate authentication from authorization, choose between stateful sessions and self-contained tokens, and design revocation, delegation, and service-to-service identity deliberately.",
    whyItMatters: "Trust has to originate somewhere, and every hop after that point is either carrying it or asserting it. The design questions all follow from that one line: whether a credential can be withdrawn before it expires, whether a token minted for billing is accepted by search, whether an offboarded employee loses read access in seconds or in the fifteen minutes their access token has left to run. Answering “we use JWTs” names a wire format and settles none of them.",
    objectives: ["Distinguish authentication, authorization, and delegation", "Choose session or token architecture from revocation and scale requirements", "Model permissions for multi-tenant and hierarchical resources", "Design service-to-service identity without shared long-lived secrets"],
    concepts: ["OAuth 2.0", "OpenID Connect", "JWT", "opaque session", "refresh token", "RBAC", "ReBAC", "mTLS", "token revocation"],
    deepDive: [
      {
        title: "Authentication, authorization, and delegation are different problems",
        summary: "Conflating them produces designs that cannot answer who granted what to whom.",
        points: [
          "Authentication establishes an identity; authorization decides whether that identity may perform an action on a resource. OAuth 2.0 is a delegation framework, not an authentication protocol—OpenID Connect is the identity layer built on top of it.",
          "An access token says what the bearer may do; an ID token says who signed in. Using an access token as proof of identity, or accepting a token whose audience names a different service, is a routine and serious mistake.",
          "Validate the issuer, the audience, the expiry, the signature, and the algorithm against a server-side allowlist before reading a single business claim. Never let the token's own `alg` header choose the verification method, and cache the JWKS for minutes rather than hours — a 24-hour key cache turns a routine rotation into a day of failed verifications or a day of trusting a retired key.",
        ],
      },
      {
        title: "Stateful sessions versus self-contained tokens",
        summary: "The choice is fundamentally about revocation latency versus lookup cost.",
        points: [
          "An opaque session ID carries no claims; every request resolves it against a session store. Revocation is immediate because the record is deleted, at the cost of a lookup on the hot path.",
          "A signed JWT is verifiable without I/O, so it scales horizontally—but it stays valid until it expires and nothing can un-issue it. A 15-minute access token backed by a longer refresh token bound to a revocable server-side record bounds an offboarded account's continued access to 15 minutes; cutting the lifetime to 5 minutes narrows that window but triples the refresh traffic the identity provider has to absorb.",
          "If you add a denylist check to make JWTs revocable, you have reintroduced the lookup and kept the complexity. Choose deliberately, and state the maximum window during which a compromised credential remains usable.",
        ],
      },
      {
        title: "Model permissions and machine identity",
        summary: "Authorization data has its own consistency and latency requirements.",
        points: [
          "RBAC assigns permissions through roles and is simple to reason about; relationship-based models answer questions like “can this user view this document because they belong to a folder's group,” which flat roles cannot express without combinatorial explosion.",
          "Centralized policy evaluation gives one auditable decision point but adds a hot dependency; distributed evaluation with replicated policy is fast but makes revocation eventually consistent. Name the staleness window—a removed employee should not keep read access for minutes.",
          "For service-to-service calls, prefer short-lived workload credentials (mTLS certificates or federated tokens) over shared static API keys. Propagate the end-user identity separately from the calling service identity so authorization can consider both.",
        ],
      },
      {
        title: "Rotate refreshes and record who acted for whom",
        summary: "Long-lived credentials and delegated actions both need a paper trail.",
        points: [
          "Rotate the refresh token on every use and remember the one you just retired. If a retired token is ever presented again, either a client raced itself or someone replayed a stolen copy, and you cannot tell which — so revoke the entire token family and force re-authentication instead of guessing.",
          "Record delegation as two identities rather than one. An administrator acting on a customer's behalf, or a job running under a service account for a specific user, should produce an audit row naming the actor, the subject, the grant that permitted it, and when that grant expires; otherwise the answer to “who did this” is a shared robot.",
        ],
      },
    ],
    tradeoffs: [
      { decision: "Opaque session vs self-contained token", preferA: "Use server-side sessions when instant revocation and fine-grained control matter.", preferB: "Use signed tokens for stateless horizontal scale and cross-service verification.", watch: "A revocation denylist on a JWT recreates the session lookup you tried to avoid." },
      { decision: "Centralized vs distributed authorization", preferA: "Centralize for auditability and consistent policy.", preferB: "Distribute replicated policy for latency and blast-radius isolation.", watch: "Replicated policy makes permission removal eventually consistent." },
      { decision: "Long vs short token lifetime", preferA: "Short access tokens bound the damage of a leaked credential.", preferB: "Longer lifetimes reduce refresh traffic and identity-provider load.", watch: "Refresh storms after a mass expiry can overload the auth service." },
    ],
    failureModes: [
      { mode: "Token accepted without audience validation", symptom: "A token minted for one service is replayed against another", mitigation: "Validate issuer and audience per service and reject unexpected values." },
      { mode: "Revoked user retains access until expiry", symptom: "Offboarded account still reads data for the token lifetime", mitigation: "Shorten access-token life, bind sessions to a revocable record, and propagate revocation events." },
      { mode: "Permission check runs after data is fetched", symptom: "Authorization filters results the caller already loaded, leaking through timing or error differences", mitigation: "Push the authorization predicate into the query and fail closed on policy-store errors." },
      { mode: "Policy store outage degrades to allow", symptom: "Every authorization check quietly returns permit while the store is unreachable, and nothing in the logs distinguishes a granted permission from an unavailable one", mitigation: "Fail closed by default, serve a bounded-TTL cache of last-known-good decisions for read paths that must survive the outage, and alarm on the fallback itself rather than only on the store." },
    ],
    interviewQuestions: ["Where does trust originate for this request?", "How long can a compromised credential remain usable?", "Who may act on behalf of whom, and how is that recorded?", "What happens if the policy store is unavailable?"],
    decisionChecklist: ["Separate authentication from authorization explicitly", "State the revocation window", "Validate issuer, audience, expiry, and algorithm", "Choose a permission model that fits resource shape", "Give services their own short-lived identity"],
    exercise: "Design authentication and authorization for a multi-tenant document product where users share folders across organizations, and state exactly how access is removed within one minute of offboarding.",
    prerequisites: ["networking", "caching-queues"],
    relatedDesigns: ["classic-file-sync", "llm-enterprise-rag", "classic-payment-ledger"],
    quiz: [
      { prompt: "Why is OAuth 2.0 alone insufficient to authenticate a user?", options: ["OAuth 2.0 has been deprecated", "It only works for mobile app clients", "It delegates access, not identity", "Its tokens are always opaque"], answerIndex: 2, explanation: "OAuth 2.0 authorizes a bearer to reach a resource; OpenID Connect adds the ID token carrying verified identity claims, which is what authentication actually needs. The frequent mistake in practice is treating an access token as proof of who signed in, which is exactly the conflation OIDC exists to fix." },
      { prompt: "What is the main operational cost of self-contained JWTs?", options: ["They need a store read per request", "They cannot be verified offline", "They cannot carry any claims", "They stay valid until they expire"], answerIndex: 3, explanation: "Stateless verification is the benefit and the cost at once: with no lookup there is no record to delete, so a compromised credential stays usable for its remaining lifetime. Answering that they need a per-request store read describes the opaque session instead — that is the model you gave up to get stateless scale." },
      { prompt: "A token minted for the billing service is presented to the search service, which accepts it. Which check was skipped?", options: ["Signature verification with JWKS keys", "Audience validation on the token", "Expiry and not-before checking", "Transport encryption using mTLS"], answerIndex: 1, explanation: "Both services trust the same issuer and the same signing keys, so the signature verifies perfectly; only the audience claim distinguishes which service a token was minted for. Assuming the signature check would have caught it is the exact misconception behind cross-service replay: a valid signature says nothing about the intended recipient." },
      { prompt: "Access tokens live 15 minutes; refresh tokens live 30 days but are bound to a revocable server-side record that is deleted at offboarding. What is the worst-case window of continued access?", options: ["Up to 15 minutes, one token life", "Zero, because revocation is instant", "Up to 30 days, the refresh life", "Until the signing key is rotated"], answerIndex: 0, explanation: "Deleting the refresh record stops renewal immediately, but the already-issued access token verifies without I/O, so access persists until it expires — 15 minutes. Answering zero is the misconception: it applies opaque-session revocation semantics to a stateless token that nothing can un-issue." },
    ],
    recallCards: [
      { id: "auth-revocation", prompt: "Explain the revocation trade-off between opaque sessions and JWTs, and how short access tokens plus refresh tokens resolve it.", answer: "An opaque session resolves against a store on every request, so deleting the record revokes access immediately at the cost of a hot-path lookup. A signed JWT verifies with no I/O and scales horizontally, but nothing can un-issue it before expiry. Issuing short-lived access tokens against a longer refresh token bound to a revocable server-side record keeps stateless verification on the hot path while bounding compromise to the access-token lifetime." },
      { id: "auth-validation", prompt: "List what must be validated on an incoming JWT, and name the validation mistake that enables cross-service replay.", answer: "Validate issuer, audience, expiry/not-before, signature, and the algorithm against a server-side allowlist, using keys from a cached rotating JWKS. Never let the token's own alg header choose the verification method. Skipping audience validation is what enables replay: a token legitimately minted for service A is presented to service B, which accepts it because it only checked the signature." },
    ],
    furtherReading: [
      { label: "RFC 6749 — OAuth 2.0", url: "https://www.rfc-editor.org/rfc/rfc6749" },
      { label: "RFC 9068 — JWT access tokens", url: "https://www.rfc-editor.org/rfc/rfc9068" },
    ],
  },
];

export const foundationPrompts: DesignPrompt[] = [
  {
    id: "url-shortener",
    title: "URL shortener",
    category: "classic",
    difficulty: "medium",
    durationMinutes: 40,
    prompt: "Design a globally available service that creates short URLs and redirects readers with very low latency. Support expiration, abuse controls, editable destinations, and asynchronous analytics.",
    requirementsToExplore: ["Custom aliases and ownership", "Redirect latency and availability", "Read-after-create behavior", "Expiration and deletion", "Analytics freshness", "Malware and abuse response"],
    expectedTopics: ["Code generation and collision policy", "Authoritative mapping schema", "Cache coherence", "Hot-link isolation", "Multi-region routing", "Asynchronous click events"],
    commonFailureModes: ["Sequential codes expose volume or become predictable", "Negative caching hides newly created aliases", "Editable links remain stale in edge caches", "A celebrity link overloads one shard", "Analytics blocks the redirect path"],
    followUpQuestions: ["How do you migrate to a longer code space?", "How do you bound read-after-write inconsistency across regions?", "What happens when abuse policy disables a heavily cached link?", "How would one customer bring a custom domain?"],
    reference: {
      diagram: {
        caption: "Redirect reads are served from edge cache with the partitioned link store as source of truth; click analytics and cache invalidation both ride asynchronous streams so neither can slow a redirect.",
        nodes: [
          { id: "client", label: "Client", kind: "client", col: 0, row: 1 },
          { id: "api", label: "Create & manage API", kind: "service", col: 1, row: 0 },
          { id: "redirect", label: "Edge redirect service", kind: "edge", col: 1, row: 2 },
          { id: "store", label: "Link store (hash-partitioned)", kind: "store", col: 2, row: 0 },
          { id: "cache", label: "Regional read cache", kind: "cache", col: 2, row: 2 },
          { id: "clicks", label: "Click event stream", kind: "stream", col: 1, row: 3 },
          { id: "log", label: "Change log (CDC)", kind: "stream", col: 3, row: 0 },
          { id: "analytics", label: "Analytics & abuse views", kind: "store", col: 3, row: 3 },
        ],
        edges: [
          { from: "client", to: "api", label: "POST /links" },
          { from: "client", to: "redirect", label: "GET /{code}" },
          { from: "api", to: "store", label: "cond. write" },
          { from: "redirect", to: "cache", label: "lookup" },
          { from: "cache", to: "store", label: "miss" },
          { from: "redirect", to: "clicks", label: "click", async: true },
          { from: "clicks", to: "analytics", label: "aggregate", async: true },
          { from: "store", to: "log", label: "CDC", async: true },
          { from: "log", to: "cache", label: "invalidate", async: true },
        ],
      },
      scope: ["Separate create/update management availability from redirect availability", "Define whether aliases are case-sensitive and reusable after deletion", "Keep click analytics off the redirect critical path"],
      apis: ["POST /links with destination, optional alias, expiry, idempotency key", "GET /{code} returns 301/302/307 according to editability and caching policy", "PATCH /links/{code} uses owner auth and expected version", "DELETE /links/{code}; analytics query reads a derived store"],
      dataModel: ["Link(code PK, destination, owner_id, created_at, expires_at, status, version)", "Unique(owner_domain, normalized_code) enforces aliases at the source", "ClickEvent(code, event_id, time_bucket, coarse_geo, referrer_class) with privacy retention", "AbuseState(code, verdict, policy_version) distributed through versioned invalidation"],
      architecture: ["Create service validates and reserves a code in the authoritative partitioned store", "Change log invalidates regional caches and updates abuse/search views", "Edge redirect service reads local cache, falls back to a regional replica/source, then emits a best-effort event", "Stream processors aggregate clicks into time-bucketed analytical storage", "Control plane manages domains, policy, and deletion independently of redirect serving"],
      invariants: ["A normalized alias maps to at most one live link", "An idempotent create returns the same code for the same request", "An older cache fill cannot overwrite a newer mapping version", "Analytics loss or slowness never blocks redirect correctness"],
      deepDives: [
        { title: "Code space", summary: "Use random or allocated numeric identifiers encoded compactly.", points: ["Seven base-62 characters provide about 3.5 trillion values; choose length from expected population and acceptable collision probability.", "Random codes need conditional insert and retry; allocated 64-bit IDs need range leasing or a Snowflake-like generator and may require obfuscation."] },
        { title: "Freshness", summary: "Mutable destinations change HTTP and cache semantics.", points: ["Immutable links can use long TTL and permanent redirects; editable links need bounded TTL, mapping versions, and versioned invalidations.", "For read-after-create, route the creator to the write region, return a consistency token, or synchronously place the mapping in the local serving cache."] },
        { title: "Hot and harmful links", summary: "The most popular key and fastest takedown drive the edge design.", points: ["Replicate hot cache entries across edge workers and coalesce misses; never let one cache key serialize all traffic.", "Abuse verdicts need a high-priority invalidation path and a short-lived deny cache; define fail-open versus fail-closed by threat level."] },
      ],
      scaling: ["Partition mappings by a hash of normalized code", "Replicate read-serving data regionally and cache at edge", "Precompute or lease ID ranges to avoid a central generator bottleneck", "Rate-limit creates and isolate tenants", "Move analytics through a partitioned stream with bounded retention"],
      observability: ["Redirect p50/p99 and success by region", "Cache hit ratio, miss coalescing, and stale-version rejection", "Create collision/conditional-write rate", "Hot-key traffic distribution", "Replication and invalidation lag", "Event drop rate and abuse-takedown propagation time"],
    },
  },
  {
    id: "distributed-rate-limiter",
    title: "Distributed rate limiter",
    category: "classic",
    difficulty: "medium",
    durationMinutes: 40,
    prompt: "Design a low-latency rate limiter for public APIs with per-user, per-tenant, and endpoint policies. Support bursts, regional deployment, live policy changes, and explicit dependency-failure behavior.",
    requirementsToExplore: ["Key and enforcement scope", "Sustained rate and burst allowance", "Accuracy and overshoot budget", "Added latency", "Policy propagation", "Fail-open/closed by endpoint"],
    expectedTopics: ["Token bucket", "Sliding-window approximation", "Atomic state transition", "Local token leasing", "Clock semantics", "Hot-tenant isolation", "Degraded mode"],
    commonFailureModes: ["One remote counter is on every critical path", "Fixed windows allow a boundary burst", "Clock rollback refills tokens", "Policy cache remains stale", "Limiter outage either drops everything or admits everything"],
    followUpQuestions: ["How do you bound global overshoot across regions?", "How are policy changes applied atomically?", "How do you protect the limiter from a hot tenant?", "What differs for login, payments, and analytics endpoints?"],
    reference: {
      diagram: {
        caption: "Each gateway decides locally from a leased quota so the hot path never blocks on the global store; the coordinator redistributes leases and bounds cross-region overshoot.",
        nodes: [
          { id: "client", label: "Client", kind: "client", col: 0, row: 1 },
          { id: "gw", label: "API gateway", kind: "edge", col: 1, row: 1 },
          { id: "local", label: "Local token bucket", kind: "cache", col: 2, row: 0 },
          { id: "policy", label: "Policy cache", kind: "cache", col: 2, row: 2 },
          { id: "coord", label: "Quota coordinator", kind: "service", col: 3, row: 1 },
          { id: "store", label: "Counter store (sharded)", kind: "store", col: 4, row: 1 },
          { id: "control", label: "Policy control plane", kind: "service", col: 4, row: 2 },
          { id: "upstream", label: "Upstream service", kind: "service", col: 2, row: 3 },
        ],
        edges: [
          { from: "client", to: "gw", label: "request" },
          { from: "gw", to: "local", label: "check" },
          { from: "local", to: "coord", label: "refill", async: true },
          { from: "coord", to: "store", label: "incr" },
          { from: "gw", to: "policy", label: "rules" },
          { from: "control", to: "policy", label: "push", async: true },
          { from: "gw", to: "upstream", label: "allow" },
          { from: "control", to: "coord", label: "limits", async: true },
        ],
      },
      scope: ["Return allow/deny, remaining budget, and retry-after", "Support hierarchical limits such as tenant plus user plus endpoint", "Define maximum overshoot and behavior when the decision store is unavailable"],
      apis: ["check(key, policy_id, cost, request_id) → decision, remaining, retry_after, policy_version", "PUT /policies/{id} with version and activation time", "Optional lease(key, tokens, epoch) for local enforcement"],
      dataModel: ["Policy(id, dimensions, algorithm, rate, burst, version, activation_time, failure_mode)", "Bucket(key, policy_version, tokens_or_count, last_refill_at_authoritative, expiry)", "Lease(key, region, amount, consumed, expires_at, epoch) for bounded distributed overshoot"],
      architecture: ["Gateway derives canonical limit keys and loads versioned policy from a local cache", "Local limiter enforces leased tokens on the request path", "Partitioned regional state store performs atomic refill-and-consume when a lease is renewed", "Global allocator divides a tenant budget into bounded regional leases", "Configuration stream invalidates policy caches and moves enforcement between epochs"],
      invariants: ["A single atomic transition never consumes more tokens than available", "Policy version used for a decision is observable", "Worst-case overshoot is bounded by outstanding leases plus in-flight decisions", "Time rollback cannot create tokens", "Failure mode is explicit per protected operation"],
      deepDives: [
        { title: "Algorithm", summary: "Token bucket represents a sustained rate with bounded burst.", points: ["Refill = min(capacity, tokens + elapsed × rate); consume only if balance covers request cost. Execute atomically per key.", "Use a monotonic clock only within one process. Shared state computes nonnegative elapsed time in the atomic store’s authoritative clock domain or logical ticks, then caps at capacity.", "A sliding-window counter interpolates adjacent buckets for a cheaper approximation; a log is exact but memory-heavy."] },
        { title: "Distributed enforcement", summary: "Locality trades exactness for latency and availability.", points: ["Leasing N tokens per region bounds overshoot by the sum of unconsumed leases while removing a cross-region call per request.", "Small leases improve global accuracy but increase allocator traffic; adapt lease size to rate and risk."] },
        { title: "Overload and failure", summary: "The limiter must not become the outage amplifier.", points: ["Use per-key sharding, request coalescing for lease renewal, quotas on config/cardinality, and bounded state TTL.", "Fail closed for abuse- or money-sensitive actions; fail open with conservative local emergency budgets for availability-sensitive reads."] },
      ],
      scaling: ["Shard state by a stable hash of policy plus subject", "Keep decisions and policy reads local to the gateway region", "Use hierarchical or leased budgets for global limits", "Apply heavier approximate sketches before exact per-key state for attack traffic", "Expire inactive keys and cap tenant cardinality"],
      observability: ["Decision latency and store dependency rate", "Allow/deny counts by policy version", "Lease utilization and estimated overshoot", "Hot-key and partition skew", "Policy propagation lag", "Fail-open/closed activations and customer-visible 429 rate"],
    },
  },
];
